Repository Seneca-CDOT/telescope, pull requests merged in 2019-11, with the labels that each got.

#68 Added some rules to '.eslintrc.js'
  .eslintrc.js
Labels: type: enhancement

#104 Enhancement (HTML/jS): modified the website
  index.html
  planet.css
  src/dialogue.js
Labels: area: front-end, type: enhancement

#46 Fixes #15: Added new file sentiment-analysis.js. Added dependencies
  package-lock.json
  package.json
  src/sentiment-analysis.js
Labels: on-board

#107 Fixes #106: ESLint errors in dialogue.js
  .eslintrc.js
  src/dialogue.js
Labels: on-board

#65 Adds Docker files as a milestone for issue-4
  .dockerignore
  Dockerfile
  docker-compose.yml
Labels: area: docker, on-board

#113 Adds Docker files
  .dockerignore
  Dockerfile
  docker-compose.yml
Labels: on-board

#97 - CI/CD Travis (#43)
  .travis.yml
  test/feed-queue.test.js
Labels: area: CI/CD, on-board

#114 Fixes 57#: Adding TO-DOs into CONTRIBUTING.md
  docs/CONTRIBUTING.md
Labels: on-board, type: documentation

#116 Tests need to close Redis connections to pass
  package-lock.json
  test/feed-queue.test.js
Labels: area: CI/CD, type: test

#125 Fixes #118: added stylelint
  .stylelintrc.js
  package-lock.json
  package.json
Labels: on-board

#137 added pagination to feed for #40
  .eslintrc.js
  index.html
  pagination.js
Labels: on-board

#157 Fix #119 - update eslint with environments currently used
  .eslintrc.js
Labels: on-board

#147 Fixes #47: Adding a CODE-OF-CONDUCT.md to the project
  CODE-OF-CONDUCT.md
Labels: on-board, type: documentation

#170 Fixes 168: Created frontend folder and moved specified files to the folder
  src/frontend/index.html
  src/frontend/pagination.js
  src/frontend/planet.css
Labels: area: front-end, on-board

#141 Fix #63: Add an Express Web Server
  package-lock.json
  package.json
  src/backend/web/app.js
  src/backend/web/routes/index.js
  src/backend/web/server.js
  test/server.test.js
Labels: area: back-end, on-board

#66 Fixes #20: Added basic summarize functionality
  package-lock.json
  package.json
  src/summarize.js
  test/summarize.test.js
Labels: area: back-end, on-board, type: enhancement

#154 Fix 45: Add CircleCI support
  .circleci/config.yml
  package-lock.json
Labels: area: CI/CD, on-board

#180 Fixes #153 - New front-end structure & design
  images/edd.png
  images/evolution.png
  images/feed-icon-10x10.png
  images/jdub.png
  images/keybuk.png
  images/logo-original.png
  images/logo.png
  images/opml.png
  images/planet.png
  images/thom.png
  src/frontend/img/logo.svg
  src/frontend/index.html
  src/frontend/planet.css
  src/frontend/style/main.css
  src/frontend/style/planet.css
Labels: area: front-end, on-board

#109 Fixes #83: test case for text-parser
  package-lock.json
  package.json
  src/text-parser.js
  test/text-parser.test.js
Labels: on-board

#93 Fix #25: Implement basic email sender
  env.example
  package-lock.json
  package.json
  src/email-sender.js
Labels: on-board

#143 Fixes #22: Inactive Blog Filter
  env.example
  feeds-redlist.json
  feeds.txt
  src/inactive-blog-filter.js
Labels: on-board

#123 Fix #74: Validate blog URLs.
  package-lock.json
  package.json
  src/utils.js
  test/utils.test.js
Labels: area: back-end, on-board

#136 Fix #59: Added feed list parser
  env.example
  src/wiki-feed-parser.js
Labels: on-board

#179 Closes #54: Fetch data from GitHub API
  env.example
  package-lock.json
  package.json
  src/github-url.js
  test/github.test.js
Labels: area: back-end, on-board, type: enhancement

#200 Fix #62: added bull board visualization route
  package-lock.json
  package.json
  src/backend/web/routes/admin.js
  src/backend/web/routes/index.js
  src/feed-queue.js
  src/index.js
Labels: area: front-end

#207 Fix #115: added test cases for sentiment analysis
  test/sentiment-analysis.test.js
Labels: type: test

#211 Added tests for inactive blog checking (#197)
  test/inactive-blog-filter.test.js
Labels: type: test

#166 Fix #94: add function for counting domains
  src/count-blog-domain.js
Labels: area: back-end, on-board

#230 Skip tests until mocked response is implemented
  test/github.test.js
Labels: area: back-end, type: bug, type: test

#227 Fix #226: Remove Explicit Parameter Bug Fix
  src/email-sender.js
Labels: type: bug

#78 Fixes #17: Implemented basic word counter & test
  package-lock.json
  package.json
  src/word-counter.js
  test/word-counter.test.js
Labels: area: back-end, on-board, type: enhancement

#135 Update CONTRIBUTING.md to specify starting Redis
  docs/CONTRIBUTING.md
Labels: area: docker, on-board, type: documentation

#254 Fixes #206 - Refactor code to use node-fetch instead of Bent
  package-lock.json
  package.json
  src/wiki-feed-parser.js
Labels: area: back-end, type: enhancement

#269 Update CONTRIBUTING with more workflow info
  docs/CONTRIBUTING.md
Labels: type: documentation

#293 Fix #280 Move jest-fetch-mock to devDependencies
  package-lock.json
  package.json
  test/lib/setupJest.js
Labels: area: back-end, type: test

#292 Added test for invalid GitHub URLs
  test/github.test.js
Labels: area: back-end, type: test

#300 Fixes #210, added nock package to mock network requests
  package.json
  test/feed-parser.test.js
Labels: area: back-end, type: test

#304 Fixes #303, removed skip from tests
  test/feed-parser.test.js
Labels: area: back-end, type: test

#306 Fix #305: Fix test failure with logger.debug()
  src/lib/queue.js
  src/lib/redis.js
Labels: area: back-end, type: bug, type: test

#302 Search bar added to Navbar instead of participants
  src/frontend/index.html
  src/frontend/style/main.css
Labels: area: front-end, type: enhancement

#311 Fix issue #310 - Remove unnecessary console message
  test/basic_analysis.test.js
Labels: area: back-end, type: test

#325 Closes #72: Adds more test cases to feedParser.test.js
  test/feed-parser.test.js
  test/fixtures.js
Labels: area: back-end, type: test

#358 move backend code from src to backend
  docs/logging.md
  package.json
  src/backend/feed/feed-parser.js
  src/backend/feed/feed-queue.js
  src/backend/feed/feed-worker.js
  src/backend/index.js
  src/backend/lib/config.js
  src/backend/lib/queue.js
  src/backend/lib/redis.js
  src/backend/login/usingPassport.js
  src/backend/utils/basic_analysis.js
  src/backend/utils/count-blog-domain.js
  src/backend/utils/email-sender.js
  src/backend/utils/extract-urls.js
  src/backend/utils/github-url.js
  src/backend/utils/inactive-blog-filter.js
  src/backend/utils/logger.js
  src/backend/utils/sanitize-html.js
  src/backend/utils/sentiment-analysis.js
  src/backend/utils/spam-checker.js
  src/backend/utils/storage.js
  src/backend/utils/summarize.js
  src/backend/utils/text-parser.js
  src/backend/utils/utils.js
  src/backend/utils/wiki-feed-parser.js
  src/backend/utils/word-counter.js
  src/backend/web/app.js
  src/backend/web/server.js
  test/basic_analysis.test.js
  test/count-blog-domain.test.js
  test/email-sender.test.js
  test/feed-parser.test.js
  test/feed-queue.test.js
  test/feed-worker.test.js
  test/github.test.js
  test/inactive-blog-filter.test.js
  test/sanitize-html.test.js
  test/sentiment-analysis.test.js
  test/spam-checker.test.js
  test/storage.test.js
  test/summarize.test.js
  test/text-parser.test.js
  test/utils.test.js
  test/word-counter.test.js
Labels: area: back-end, type: enhancement

#360 Fixes #359: Rename files in src/feed/ to drop feed- prefix
  src/backend/feed/parser.js
  src/backend/feed/queue.js
  src/backend/feed/worker.js
  src/backend/index.js
  src/backend/utils/inactive-blog-filter.js
  test/feed-parser.test.js
  test/feed-queue.test.js
  test/feed-worker.test.js
Labels: area: back-end
