Repository Seneca-CDOT/telescope, pull requests merged in 2021-03, with the labels that each got.

#1854 Issue #1677 UI 2.0 Posts,Timeline and Post
  src/web/src/components/Posts/Post.tsx
  src/web/src/components/Posts/Timeline.tsx
  src/web/src/components/Posts/index.tsx
Labels: area: front-end, area: nextjs

#1863 Fix #1861 -Merging desktop and mobile headers
  src/web/src/components/Header/MobileHeader.tsx
  src/web/src/components/Header/index.tsx
  src/web/src/components/Login/LoggedIn.tsx
  src/web/src/components/Login/LoggedOut.tsx
  src/web/src/components/NavBar/NavBarButton.tsx
  src/web/src/components/NavBar/index.tsx
  src/web/src/pages/_app.tsx
Labels: area: front-end

#1867 Fix the horizontal scroll bar on Linux and Windows.
  src/web/src/components/Posts/index.tsx
Labels: area: front-end, area: nextjs, type: bug

#1796 Authentication/Authorization microservice
  .circleci/config.yml
  .dockerignore
  .eslintrc.js
  .github/workflows/node-js-ci.yml
  README.md
  babel.config.js
  docker-compose-production.yml
  docker-compose.yml
  docs/project-board.md
  jest-playwright.config.js
  jest.config.base.js
  jest.config.e2e.js
  jest.config.js
  jest.setup.js
  package.json
  src/api/auth/.dockerignore
  src/api/auth/Dockerfile
  src/api/auth/config/saml20-idp-hosted.php
  src/api/auth/config/simplesamlphp-users.php
  src/api/auth/jest-playwright.config.js
  src/api/auth/jest.config.e2e.js
  src/api/auth/jest.config.js
  src/api/auth/jest.setup.js
  src/api/auth/package.json
  src/api/auth/src/admin.js
  src/api/auth/src/authentication.js
  src/api/auth/src/authorization.js
  src/api/auth/src/hash.js
  src/api/auth/src/index.js
  src/api/auth/src/routes.js
  src/api/auth/src/server.js
  src/api/auth/src/token.js
  src/api/auth/src/user.js
  src/api/auth/test/e2e/auth-flows.test.js
  src/api/auth/test/e2e/index.html
  src/api/auth/test/e2e/routes.test.js
  src/api/auth/test/manual/index.html
  src/api/auth/test/manual/script.js
  src/api/auth/test/token.test.js
  src/api/docker-compose.yml
  src/api/env.development
  src/api/env.production
  src/api/env.staging
  src/api/production.yml
  src/web/jest.config.js
  test/jest.config.js
Labels: area: back-end, area: docker, area: microservices, area: web server, type: security, type: test

#1860 Fix #1857 - Remove SWRInfinite and any type
  src/web/src/hooks/use-telescope-contributor.ts
Labels: area: front-end

#1875 New logo update
  src/web/public/icons/apple-icon-180.png
  src/web/public/icons/apple-splash-1125-2436.jpg
  src/web/public/icons/apple-splash-1136-640.jpg
  src/web/public/icons/apple-splash-1170-2532.jpg
  src/web/public/icons/apple-splash-1242-2208.jpg
  src/web/public/icons/apple-splash-1242-2688.jpg
  src/web/public/icons/apple-splash-1284-2778.jpg
  src/web/public/icons/apple-splash-1334-750.jpg
  src/web/public/icons/apple-splash-1536-2048.jpg
  src/web/public/icons/apple-splash-1620-2160.jpg
  src/web/public/icons/apple-splash-1668-2224.jpg
  src/web/public/icons/apple-splash-1668-2388.jpg
  src/web/public/icons/apple-splash-1792-828.jpg
  src/web/public/icons/apple-splash-2048-1536.jpg
  src/web/public/icons/apple-splash-2048-2732.jpg
  src/web/public/icons/apple-splash-2160-1620.jpg
  src/web/public/icons/apple-splash-2208-1242.jpg
  src/web/public/icons/apple-splash-2224-1668.jpg
  src/web/public/icons/apple-splash-2388-1668.jpg
  src/web/public/icons/apple-splash-2436-1125.jpg
  src/web/public/icons/apple-splash-2532-1170.jpg
  src/web/public/icons/apple-splash-2688-1242.jpg
  src/web/public/icons/apple-splash-2732-2048.jpg
  src/web/public/icons/apple-splash-2778-1284.jpg
  src/web/public/icons/apple-splash-640-1136.jpg
  src/web/public/icons/apple-splash-750-1334.jpg
  src/web/public/icons/apple-splash-828-1792.jpg
  src/web/public/icons/manifest-icon-192.png
  src/web/public/icons/manifest-icon-512.png
  src/web/public/logo-badged.svg
  src/web/public/logo.svg
  src/web/public/logoImages/apple-icon-180.png
  src/web/public/logoImages/apple-splash-1125-2436.jpg
  src/web/public/logoImages/apple-splash-1136-640.jpg
  src/web/public/logoImages/apple-splash-1170-2532.jpg
  src/web/public/logoImages/apple-splash-1242-2208.jpg
  src/web/public/logoImages/apple-splash-1242-2688.jpg
  src/web/public/logoImages/apple-splash-1284-2778.jpg
  src/web/public/logoImages/apple-splash-1334-750.jpg
  src/web/public/logoImages/apple-splash-1536-2048.jpg
  src/web/public/logoImages/apple-splash-1620-2160.jpg
  src/web/public/logoImages/apple-splash-1668-2224.jpg
  src/web/public/logoImages/apple-splash-1668-2388.jpg
  src/web/public/logoImages/apple-splash-1792-828.jpg
  src/web/public/logoImages/apple-splash-2048-1536.jpg
  src/web/public/logoImages/apple-splash-2048-2732.jpg
  src/web/public/logoImages/apple-splash-2160-1620.jpg
  src/web/public/logoImages/apple-splash-2208-1242.jpg
  src/web/public/logoImages/apple-splash-2224-1668.jpg
  src/web/public/logoImages/apple-splash-2388-1668.jpg
  src/web/public/logoImages/apple-splash-2436-1125.jpg
  src/web/public/logoImages/apple-splash-2532-1170.jpg
  src/web/public/logoImages/apple-splash-2688-1242.jpg
  src/web/public/logoImages/apple-splash-2732-2048.jpg
  src/web/public/logoImages/apple-splash-2778-1284.jpg
  src/web/public/logoImages/apple-splash-640-1136.jpg
  src/web/public/logoImages/apple-splash-750-1334.jpg
  src/web/public/logoImages/apple-splash-828-1792.jpg
  src/web/public/logoImages/manifest-icon-192.png
  src/web/public/logoImages/manifest-icon-512.png
Labels: area: design, area: front-end, area: nextjs

#1876 Fixes: BUG - vertical scroll bar on post
  src/web/src/components/Posts/Post.tsx
Labels: area: front-end, area: nextjs, type: bug

#1830 Closes #1705: Add Let's Encrypt to Traefik Microservices router
  src/api/config/certs.yml
  src/api/env.production
  src/api/env.staging
  src/api/production.yml
Labels: area: microservices

#1878 Added Dependabot config for Docker, GitHub Actions, and more npm packages
  .github/dependabot.yml
Labels: Priority: Medium, area: tools, dependencies, developer experience, type: enhancement

#1893 Add unit tests for image service
  src/api/image/Dockerfile
  src/api/image/jest.config.js
  src/api/image/package.json
  src/api/image/server.js
  src/api/image/src/index.js
  src/api/image/src/routes/image.js
  src/api/image/src/server.js
  src/api/image/test/gallery.test.js
  src/api/image/test/image.test.js
Labels: area: microservices, type: test

#1905 Mobile version posts timeline post
  src/web/src/components/NavBar/index.tsx
  src/web/src/components/Posts/Post.tsx
  src/web/src/components/Posts/PostInfo.tsx
  src/web/src/components/Posts/Timeline.tsx
  src/web/src/components/Posts/index.tsx
Labels: area: front-end, area: nextjs

#1906 Banner 1.8
  src/web/src/components/Banner.tsx
  src/web/src/components/BannerDynamicItems.tsx
Labels: area: front-end, area: nextjs

#1839 Changed Search bar style for new UI [1805 - DESKTOP UI]
  src/web/src/components/SearchBar.tsx
  src/web/src/components/SearchInput/AuthorSearchInput.tsx
  src/web/src/components/SearchInput/PostSearchInput.tsx
Labels: area: nextjs

#1911 Fix issue #1855: add temporary avatar
  src/web/src/components/Posts/Post.tsx
  src/web/src/components/Posts/PostAvatar.tsx
  src/web/src/components/Posts/PostInfo.tsx
Labels: area: front-end, area: nextjs

#1916 Fixes #1689: port 'BackToTop' button to UI2.0
  src/web/src/components/BackToTopButton.tsx
  src/web/src/components/Banner.tsx
Labels: area: css styling, area: front-end, area: nextjs

#1838 Adds Initial Service to Get Posts
  package.json
  src/api/docker-compose.yml
  src/api/env.development
  src/api/env.production
  src/api/env.staging
  src/api/posts/.dockerignore
  src/api/posts/Dockerfile
  src/api/posts/README.md
  src/api/posts/jest.config.js
  src/api/posts/jest.setup.js
  src/api/posts/package.json
  src/api/posts/src/data/post.js
  src/api/posts/src/index.js
  src/api/posts/src/libs/redis.js
  src/api/posts/src/routes/posts.js
  src/api/posts/src/server.js
  src/api/posts/src/storage.js
  src/api/posts/src/text-parser.js
  src/api/posts/src/validation.js
  src/api/posts/test/posts.test.js
Labels: area: CI/CD, area: back-end, area: deployment, area: microservices

#1923 Fix: issue 1919 - Center initials
  src/web/src/components/Posts/PostAvatar.tsx
Labels: area: front-end

#1941 Make services scripts work on Windows
  package.json
Labels: developer experience, type: bug

#1833 Added Service for Auto Discovery of Feeds for URLs
  config/env.development
  config/env.production
  config/env.staging
  docker/docker-compose.yml
  package.json
  src/api/feed-discovery/.dockerignore
  src/api/feed-discovery/Dockerfile
  src/api/feed-discovery/README.md
  src/api/feed-discovery/jest.config.js
  src/api/feed-discovery/package.json
  src/api/feed-discovery/src/index.js
  src/api/feed-discovery/src/lib.js
  src/api/feed-discovery/src/router.js
  src/api/feed-discovery/src/server.js
  src/api/feed-discovery/test/lib.test.js
  src/api/feed-discovery/test/router.test.js
Labels: area: back-end, area: microservices

#1935 Remove nginx from development.yml, update docs
  config/nginx.development.conf
  config/nginx.production.conf.template
  docker/development.yml
  docker/docker-compose.yml
  docker/production.yml
  src/api/readme.md
  tools/services.js
Labels: area: docker

#1933 Fix: expose ports in development
  docker/development.yml
Labels: Priority: High, developer experience

#1948 Fixed typo in changelog configuration file
  release-changelog-builder-config.json
Labels: 5 min fix, area: CI/CD, type: bug

#1952 Configure staging/Vercel to use new auth service
  Dockerfile
  config/env.staging
  docker/production.yml
  src/web/src/config.ts
Labels: area: deployment, area: microservices, area: nextjs, type: security

#1953 Updated front-end to use posts microservice
  Dockerfile
  docker/docker-compose.yml
  docker/production.yml
  src/api/posts/package.json
  src/api/posts/src/data/feed.js
  src/api/posts/src/data/post.js
  src/api/posts/src/routes/posts.js
  src/api/posts/test/posts.test.js
  src/web/next.config.js
  src/web/src/components/Posts/Timeline.tsx
  src/web/src/components/Posts/index.tsx
  src/web/src/config.ts
Labels: area: microservices

#1954 Use proper AUTH_URL values in next.config.js and AuthProvider
  config/env.development
  config/env.production
  config/env.staging
  src/api/feed-discovery/README.md
  src/api/feed-discovery/src/server.js
  src/web/next.config.js
  src/web/src/components/AuthProvider.tsx
Labels: area: deployment, area: docker, area: nextjs

#1964 Fixes #1959: Blue/Green deployment only does blue deployments
  tools/autodeployment/deploy.sh
Labels: Priority: High, area: autodeployment

#1962 Added new keywords, robots.txt, optimized meta tags
  src/web/public/robots.txt
  src/web/src/components/SEO.tsx
  src/web/src/config.ts
  src/web/src/pages/_document.tsx
  src/web/src/pages/about.mdx
  src/web/src/pages/myfeeds.tsx
  src/web/src/pages/search.tsx
Labels: area: front-end, type: enhancement

#1969 Package UI 1.8.1
  src/web/src/components/BackToTopButton.tsx
  src/web/src/components/NavBar/index.tsx
  src/web/src/components/Posts/Post.tsx
  src/web/src/components/Posts/PostAvatar.tsx
Labels: area: front-end

#1915 Closes #1642 - Adds User Microservice
  config/env.development
  config/env.production
  config/env.staging
  docker/docker-compose.yml
  docker/production.yml
  package.json
  src/api/readme.md
  src/api/users/.dockerignore
  src/api/users/.gitignore
  src/api/users/Dockerfile
  src/api/users/README.md
  src/api/users/index.js
  src/api/users/jest.config.e2e.js
  src/api/users/package.json
  src/api/users/server.js
  src/api/users/src/models/celebrateSchema.js
  src/api/users/src/models/users.js
  src/api/users/src/routes/users.js
  src/api/users/src/services/firestore.js
  src/api/users/test/e2e/users.test.js
Labels: area: back-end, area: microservices, satellite

#1980 Fix: change our husky settings to work with v5
  .husky/.gitignore
  .husky/pre-commit
  package.json
Labels: developer experience

#1958 Reduce test log spam
  src/backend/lib/config.js
  src/backend/web/routes/admin.js
  src/backend/web/routes/index.js
Labels: developer experience, type: test

#1961 Reactivated Dark Theme
  docs/front-end.md
  src/web/src/components/Banner.tsx
  src/web/src/components/BannerDynamicItems.tsx
  src/web/src/components/DynamicImage.tsx
  src/web/src/components/NavBar/NavBarButton.tsx
  src/web/src/components/NavBar/index.tsx
  src/web/src/components/Posts/Post.tsx
  src/web/src/components/Posts/PostAvatar.tsx
  src/web/src/components/Posts/index.tsx
  src/web/src/components/ThemeToggleButton.tsx
  src/web/src/theme/index.ts
Labels: area: front-end, area: nextjs

#1986 Update autodeployment deps, remove body-parser
  tools/autodeployment/package.json
  tools/autodeployment/server.js
Labels: area: autodeployment, dependencies

#1982 Fix #1872: pass state with login flow
  src/web/package.json
  src/web/src/components/AuthProvider.tsx
Labels: area: front-end, type: security

#1993 Added missing domain to the image url
  src/web/src/config.ts
  src/web/src/pages/_document.tsx
Labels: Priority: Medium, type: bug

#1979 Fixes #1977 - Set minimum post height
  src/web/src/components/Posts/Post.tsx
Labels: area: nextjs

#1978 Add Cache-Control to status service
  src/api/status/package.json
  src/api/status/src/server.js
Labels: area: microservices, area: performance

#1997 Quick Users MS Fix(es)
  src/api/users/package.json
  src/api/users/src/index.js
  src/api/users/src/server.js
  src/api/users/test/e2e/users.test.js
Labels: 5 min fix, area: microservices

#1910 Fixes #1791: Handling with inline img
  src/web/src/styles/telescope-post-content.css
Labels: area: css styling, area: front-end, area: nextjs

#1967 Minor About Page CSS Touchup
  src/web/src/pages/about.mdx
  src/web/src/pages/layouts/MDXPageBase.tsx
Labels: area: front-end

#2006 Shrink the title font-size; add author blog link to avatar
  src/web/src/components/Posts/Post.tsx
  src/web/src/components/Posts/PostAvatar.tsx
  src/web/src/components/Posts/PostInfo.tsx
Labels: area: css styling, area: front-end

#2017 Correct avatar link in postInfo and rename avatar prop
  src/web/src/components/Posts/Post.tsx
  src/web/src/components/Posts/PostAvatar.tsx
  src/web/src/components/Posts/PostInfo.tsx
Labels: area: front-end, type: bug

#2018 Add Admin Buttons
  src/web/src/components/AdminButtons.tsx
  src/web/src/components/Posts/Post.tsx
  src/web/src/components/Posts/PostInfo.tsx
Labels: area: css styling, area: front-end, type: enhancement

#1909 Fixes #1807: [UI 2.0] SearchHelp
  src/web/src/components/SearchHelp.tsx
  src/web/src/components/SearchPage.tsx
Labels: area: front-end, area: nextjs

#2029 Change color for search bar in dark mode
  src/web/src/components/SearchBar.tsx
Labels: area: css styling, type: bug

#2031 Improve user accessibility of link to AAA
  src/web/src/components/Posts/Post.tsx
Labels: area: css styling, area: design, type: bug

#2036 Added Google Search Console ownership verification
  src/web/public/googlee1d86717a49db532.html
Labels: area: front-end

#2025 Fixes #2002: Don't center table contents in figure
  src/web/src/styles/telescope-post-content.css
Labels: area: css styling, area: front-end, type: enhancement

#2034 Added initial setup for Jest Snapshot testing
  babel.config.js
  package.json
  src/web/jest.config.js
  src/web/package.json
  src/web/src/components/Logo.test.tsx
  src/web/src/components/__snapshots__/Logo.test.tsx.snap
  src/web/tsconfig.jest.json
Labels: area: front-end, type: test

#2023 Closes #1744: Explore using Portainer to allow admins to manage docker containers
  config/nginx.conf.template
  docker/production.yml
Labels: area: microservices

#2026 Fixes #1955: Replace normal hyphen with a non-breaking hyphen
  src/web/src/components/Posts/PostInfo.tsx
Labels: area: front-end, area: nextjs, type: bug

#2027 Closes Issue #1932: Added environment variables to prod's Docker file
  config/env.development
  config/env.production
  config/env.staging
  docker/development.yml
  docker/production.yml
  src/api/users/README.md
  src/api/users/jest.config.e2e.js
  src/api/users/package.json
  src/api/users/src/services/firestore.js
Labels: area: microservices

#2052 env.development fix: ELASTIC_PORT was commented.
  config/env.development
Labels: area: back-end, area: microservices

#2057 Fix path issus in production
  docker/production.yml
Labels: Priority: High, area: deployment, area: microservices

#2046 Fixes #1584: Create a SearchContext to pass props more easily to Search Components
  src/web/src/components/SearchBar.tsx
  src/web/src/components/SearchInput/AuthorSearchInput.tsx
  src/web/src/components/SearchInput/PostSearchInput.tsx
  src/web/src/components/SearchInput/SearchInput.tsx
  src/web/src/components/SearchPage.tsx
  src/web/src/components/SearchProvider.tsx
  src/web/src/components/SearchResults.tsx
  src/web/src/hooks/use-search-value.ts
  src/web/src/pages/search.tsx
Labels: area: front-end, area: nextjs, type: enhancement, type: nice to have
