Repository Seneca-CDOT/telescope, pull requests merged in 2021-04, with the labels that each got.

#2061 Increase letter-spacing for telescope-post-content
  src/web/src/styles/telescope-post-content.css
Labels: area: css styling, area: front-end

#2022 Fixes issue-1929: Paginated get route
  src/api/users/README.md
  src/api/users/src/models/celebrateSchema.js
  src/api/users/src/routes/users.js
  src/api/users/test/e2e/users.test.js
Labels: area: microservices

#2064 Add jest:e2e-watch script
  package.json
Labels: developer experience, type: test

#2067 remove backToTop button
  src/web/src/components/BackToTopButton.tsx
  src/web/src/components/SearchPage.tsx
  src/web/src/pages/index.tsx
  src/web/src/pages/myfeeds.tsx
Labels: area: front-end

#2070 Removed unused component
  src/web/src/components/Footer.tsx
Labels: area: front-end

#2073 Update Posts service deps
  src/api/posts/package.json
Labels: area: microservices, dependencies

#2074 Update web deps + webpack version to 5
  src/web/next.config.js
  src/web/package.json
Labels: area: front-end

#2071 Update Users service deps
  src/api/users/package.json
Labels: area: microservices, dependencies

#2072 Update auth deps
  src/api/auth/package.json
Labels: area: microservices, dependencies

#2075 Fix search page for vercel.
  docker/production.yml
  src/backend/utils/indexer.js
Labels: Priority: High, area: back-end, area: front-end

#2040 Fixes #1975: Decorate each post with a class that matches the blog host platform
  src/web/src/components/Posts/Post.tsx
Labels: area: css styling, area: front-end

#2060 Use hashed email as id for Users in Firestore
  docker/docker-compose.yml
  src/api/users/env.local
  src/api/users/jest.config.js
  src/api/users/package.json
  src/api/users/src/models/celebrateSchema.js
  src/api/users/src/models/schema.js
  src/api/users/src/models/user.js
  src/api/users/src/models/users.js
  src/api/users/src/routes/users.js
  src/api/users/src/services/firestore.js
  src/api/users/src/util.js
  src/api/users/test/e2e/users.test.js
  src/api/users/test/user.test.js
  src/api/users/test/util.test.js
Labels: area: microservices, type: security

#2078 Landing page 2.0
  src/web/src/components/Banner.tsx
  src/web/src/components/BannerButtons.tsx
  src/web/src/components/BannerDynamicItems.tsx
  src/web/src/components/DynamicImage.tsx
  src/web/src/components/Posts/PostAvatar.tsx
  src/web/src/components/ScrollAction.tsx
  src/web/src/components/SearchPage.tsx
Labels: area: front-end

#2089 Remove /myfeeds page, components, and deps
  src/web/package.json
  src/web/src/components/DeleteFeedDialogButton.tsx
  src/web/src/components/ExistingFeedList.tsx
  src/web/src/components/HelpPopoverButton.tsx
  src/web/src/components/Login/LoggedIn.tsx
  src/web/src/components/MyFeeds.tsx
  src/web/src/components/SnackBar.tsx
  src/web/src/interfaces/index.ts
  src/web/src/pages/myfeeds.tsx
Labels: area: front-end

#2066 Fixes: #2062: Search bar fires a request on every entered letter
  src/web/src/components/SearchProvider.tsx
  src/web/src/components/SearchResults.tsx
Labels: area: front-end

#2091 Fixes #2039: BlogSpot images are scaled down the same as inline images
  src/web/src/styles/telescope-post-content.css
Labels: area: css styling, type: bug

#2058 Add proper roles and User service to JWT authorization
  docker/development.yml
  docker/docker-compose.yml
  src/api/auth/env.local
  src/api/auth/package.json
  src/api/auth/src/admin.js
  src/api/auth/src/authentication.js
  src/api/auth/src/authorization.js
  src/api/auth/src/index.js
  src/api/auth/src/routes.js
  src/api/auth/src/token.js
  src/api/auth/src/user.js
  src/api/auth/test/e2e/auth-flows.test.js
  src/api/auth/test/e2e/routes.test.js
  src/api/auth/test/manual/script.js
  src/api/auth/test/token.test.js
  src/api/auth/test/user.test.js
Labels: Blocked, area: microservices, satellite, type: security

#2088 Rework User to use proper JWT payload data
  src/web/src/User.ts
  src/web/src/components/BannerButtons.tsx
Labels: area: front-end

#2098 Fix login on localhost, add WEB_URL env variable support
  Dockerfile
  config/env.development
  config/env.production
  config/env.staging
  docker/production.yml
  src/web/next.config.js
  src/web/src/components/AuthProvider.tsx
  src/web/src/components/SEO.tsx
  src/web/src/config.ts
  src/web/src/pages/error.tsx
Labels: area: docker, developer experience, type: security

#2081 Update environment-setup
  docs/environment-setup.md
Labels: developer experience, type: documentation (docs)

#2103 Fix how we mock fetch in Jest
  jest.config.base.js
  jest.setup.js
  test/jest.config.js
  test/jest.setup.js
Labels: developer experience, type: test

#2101 Update access token with more user details for front-end
  config/simplesamlphp-users.php
  src/api/auth/src/authentication.js
  src/api/auth/src/routes.js
  src/api/auth/src/token.js
  src/api/auth/src/user.js
  src/api/auth/test/e2e/auth-flows.test.js
  src/api/auth/test/token.test.js
  src/api/auth/test/user.test.js
  src/web/src/User.ts
Labels: area: back-end, area: front-end

#2104 Don't use / as webUrl, prefer NEXT_PUBLIC_WEB_URL or VERCEL_URL
  src/web/next.config.js
  src/web/src/config.ts
  src/web/vercel.json
Labels: area: autodeployment

#2099 Allow Vercel preview PR URLs for auth redirects on staging
  config/env.staging
  src/api/auth/package.json
  src/api/auth/src/middleware.js
  src/api/auth/src/routes.js
  src/api/auth/src/util.js
  src/api/auth/test/util.test.js
Labels: area: deployment, type: security

#2096 Closes #2083: Migrate legacy accounts away from wiki
  tools/migrate/.gitignore
  tools/migrate/README.md
  tools/migrate/migrate.js
  tools/migrate/package.json
Labels: area: back-end, area: microservices, area: tools

#2107 Don't assume https:// for WEB_URL
  src/web/next.config.js
Labels: type: bug

#2105 Fix: Dark mode not being applied fully when user logs in
  src/web/src/components/BannerButtons.tsx
  src/web/src/components/TelescopeAvatar.tsx
Labels: area: front-end, type: bug

#1828 Post parsing/sync microservice
  config/env.development
  config/env.production
  config/env.staging
  docker/development.yml
  docker/docker-compose.yml
  docker/production.yml
  package.json
  src/api/parser/.dockerignore
  src/api/parser/Dockerfile
  src/api/parser/jest.config.e2e.js
  src/api/parser/jest.config.js
  src/api/parser/package.json
  src/api/parser/readme.md
  src/api/parser/src/data/article-error.js
  src/api/parser/src/data/feed.js
  src/api/parser/src/data/post.js
  src/api/parser/src/feed/processor.js
  src/api/parser/src/feed/queue.js
  src/api/parser/src/feed/worker.js
  src/api/parser/src/index.js
  src/api/parser/src/lib/elastic.js
  src/api/parser/src/lib/queue.js
  src/api/parser/src/lib/shutdown.js
  src/api/parser/src/parser-queue.js
  src/api/parser/src/server.js
  src/api/parser/src/storage.js
  src/api/parser/src/text-parser.js
  src/api/readme.md
Labels: area: microservices

#2094 Only show navbar when scrolls to post
  src/web/src/components/Banner.tsx
  src/web/src/components/NavBar/index.tsx
  src/web/src/pages/_app.tsx
  src/web/src/pages/about.mdx
  src/web/src/pages/index.tsx
  src/web/src/pages/layouts/MDXPageBase.tsx
  src/web/src/pages/search.tsx
Labels: area: front-end

#2113 Fix: add MS search info to env.staging and env.production
  config/env.production
  config/env.staging
Labels: Priority: High, area: autodeployment

#2115 Updated satellite semver in /src/api/auth/package.json
  src/api/auth/package.json
Labels: 5 min fix

#2119 Added Jest plugin to Eslint config
  .eslintrc.js
  src/web/package.json
Labels: developer experience

#2125 Added dependabot configs for all services
  .github/dependabot.yml
Labels: area: tools, type: enhancement

#2127 Update autodeployment deps to clear netmask security vulnerability
  tools/autodeployment/package.json
Labels: area: autodeployment, dependencies, type: security

#2122 Switched to react testing library for FE tests
  package.json
  src/web/package.json
  src/web/src/components/AboutFooter.test.tsx
  src/web/src/components/Logo.test.tsx
  src/web/src/components/__snapshots__/AboutFooter.test.tsx.snap
  src/web/src/components/__snapshots__/Logo.test.tsx.snap
Labels: area: front-end

#2133 Use Redis for auth service session storage in production
  src/api/auth/package.json
  src/api/auth/src/index.js
Labels: area: deployment, area: microservices, area: redis, satellite

#2139 Fix #2138: iat should be less than or equal to now
  src/api/auth/test/token.test.js
Labels: type: bug, type: test

#2093 Add e2e test for signup flow in auth + user services
  src/api/auth/test/e2e/auth-flows.test.js
  src/api/auth/test/e2e/signup-flow.test.js
  src/api/auth/test/e2e/utils.js
  src/api/users/package.json
  src/api/users/src/routes/users.js
Labels: area: microservices, type: security, type: test

#2137 Minor UI update
  src/web/src/components/Banner.tsx
  src/web/src/components/BannerButtons.tsx
  src/web/src/components/Posts/index.tsx
  src/web/src/components/TelescopeAvatar.tsx
Labels: area: front-end

#2142 Update auth tests to more closely match signup requirements
  docker/development.yml
  jest-playwright.config.js
  jest.config.e2e.js
  package.json
  src/api/auth/jest.config.e2e.js
  src/api/auth/package.json
  src/api/auth/test/e2e/auth-flows.test.js
  src/api/auth/test/e2e/signup-flow.test.js
  src/api/auth/test/e2e/utils.js
  test/test-web-content/auth.html
  test/test-web-content/blog.html
  test/test-web-content/feed.xml
  test/test-web-content/index.html
  test/test-web-content/manual-auth/index.html
  test/test-web-content/manual-auth/script.js
Labels: area: microservices, type: test

#2150 Fix landing page on mobile
  src/web/src/components/Banner.tsx
Labels: area: front-end

#2145 Add users container to depends_on for auth docker service
  docker/docker-compose.yml
Labels: area: docker

#2144 Add authorization middlware to parser service
  src/api/parser/src/index.js
Labels: area: microservices, type: security

#2140 Fixes #2014: Adds search service to the front-end
  Dockerfile
  docker/production.yml
  src/api/search/src/routes/query.js
  src/api/search/src/search.js
  src/web/next.config.js
  src/web/src/components/SearchResults.tsx
  src/web/src/config.ts
Labels: area: front-end, area: microservices

#2152 Improve color contrast in search help
  src/web/src/components/SearchHelp.tsx
Labels: accessibility, area: css styling, area: front-end, type: bug

#2151 Fix #1968 update Unsplash photos list for image service
  src/api/image/unsplash-photos.json
Labels: area: microservices

#2158 fixes #2157 - Align post content on mobile under 600px
  src/web/src/components/Posts/Post.tsx
Labels: area: front-end, type: bug

#2161 Fix docker environment for search service
  docker/development.yml
  docker/docker-compose.yml
Labels: area: elasticsearch, area: microservices, type: bug

#2035 CSS changes to author info section
  src/web/src/components/Posts/PostInfo.tsx
Labels: area: front-end

#2163 Fixes #1983: Improve SearchHelp logic
  src/web/src/components/SearchPage.tsx
  src/web/src/components/SearchProvider.tsx
  src/web/src/components/SearchResults.tsx
Labels: area: front-end, type: enhancement

#2167 Don't crash on SAML logout error, log and redirect
  src/api/auth/src/routes/logout.js
Labels: area: microservices

#2159 Fix: Remove remaining volumes/images/contaniers in every deployment
  tools/autodeployment/deploy.sh
Labels: area: autodeployment, area: deployment

#2148 SignUp Page
  docker/production.yml
  src/web/next.config.js
  src/web/package.json
  src/web/src/components/AuthProvider.tsx
  src/web/src/components/BannerButtons.tsx
  src/web/src/components/PopUp.tsx
  src/web/src/components/SignUp/FormFields/CheckBoxInput.tsx
  src/web/src/components/SignUp/FormFields/TextInput.tsx
  src/web/src/components/SignUp/FormFields/index.tsx
  src/web/src/components/SignUp/Forms/BasicInfo.tsx
  src/web/src/components/SignUp/Forms/GitHubAccount.tsx
  src/web/src/components/SignUp/Forms/Overview.tsx
  src/web/src/components/SignUp/Forms/RSSFeeds.tsx
  src/web/src/components/SignUp/Forms/Review.tsx
  src/web/src/components/SignUp/Forms/index.tsx
  src/web/src/components/SignUp/Schema/FormModel.tsx
  src/web/src/components/SignUp/Schema/FormSchema.tsx
  src/web/src/components/TelescopeAvatar.tsx
  src/web/src/config.ts
  src/web/src/interfaces/index.ts
  src/web/src/pages/signup.tsx
Labels: area: back-end, area: front-end, area: microservices

#2033 Added PWA
  src/web/.gitignore
  src/web/next.config.js
  src/web/package.json
  src/web/public/manifest.json
  src/web/src/pages/_document.tsx
  src/web/webpack.config.js
Labels: area: PWA

#2130 Fixes #2001: Added bottom padding to improve visual break
  src/web/src/components/Posts/Post.tsx
Labels: Priority: High, area: design, area: front-end, type: enhancement

#2165 Fixes #1938: Updated healthCheck for Posts service
  src/api/posts/src/index.js
  src/api/posts/src/libs/redis.js
  src/api/posts/src/redis.js
  src/api/posts/src/routes/posts.js
  src/api/posts/src/storage.js
Labels: area: microservices

#2175 Fix Banner Observer and NavBar rendering when using snap-scroll or scroll down button.
  src/web/src/components/Banner.tsx
Labels: area: front-end

#2184 Improve contrast ratio in contributor card and search results message
  src/web/src/components/GitHubContributorCard.tsx
  src/web/src/components/Posts/Timeline.tsx
  src/web/src/components/SearchResults.tsx
  src/web/src/theme/index.ts
Labels: accessibility, area: front-end, type: bug

#2188 Fixes #2186: Signup Flow fails with feed-discovery
  Dockerfile
Labels: Priority: High, area: front-end, area: microservices

#2173 Closes #2054: Fix users MS e2e tests
  src/api/users/jest.config.e2e.js
  src/api/users/src/routes/users.js
  src/api/users/test/e2e/users.test.js
  src/api/users/test/e2e/utils.js
Labels: area: microservices, type: test

#2190 Fix part of 2171 signup flow styles
  src/web/package.json
  src/web/src/components/SignUp/Forms/BasicInfo.tsx
  src/web/src/components/SignUp/Forms/GitHubAccount.tsx
  src/web/src/components/SignUp/Forms/Overview.tsx
  src/web/src/components/SignUp/Forms/RSSFeeds.tsx
  src/web/src/components/SignUp/Forms/Review.tsx
  src/web/src/pages/signup.tsx
Labels: area: front-end

#2191 Fix #2189 - Use correct font for version in header
  src/web/src/components/Banner.tsx
Labels: area: front-end

#2192 Fixes # 2155: Improved postInfo grid size to fit bigger names on mobile
  src/web/src/components/AdminButtons.tsx
  src/web/src/components/Posts/Post.tsx
Labels: area: front-end

#2176 Fixes #2169: Rename blog prop to url in PostAvatar, deal with optional value
  src/web/src/components/Posts/Post.tsx
  src/web/src/components/Posts/PostAvatar.tsx
  src/web/src/components/Posts/PostInfo.tsx
  src/web/src/components/SignUp/Forms/GitHubAccount.tsx
  src/web/src/components/SignUp/Forms/Review.tsx
Labels: area: front-end, type: enhancement

#2194 Fix banner buttons on mobile
  src/web/src/components/Banner.tsx
  src/web/src/components/BannerButtons.tsx
Labels: area: front-end

#2202 This PR adresses #2201: Extra width causing horizontal overflow
  src/web/src/components/Posts/Post.tsx
  src/web/src/components/Posts/PostInfo.tsx
Labels: area: front-end, type: bug

#2203 This PR adresses #2171: Fix styles on SignUp page
  src/web/src/components/PopUp.tsx
Labels: area: front-end

#2200 fix #2050: Improve slack icon contrast ratio
  src/web/package.json
  src/web/public/slack-logo.svg
  src/web/src/components/AboutFooter.tsx
  src/web/src/components/__snapshots__/AboutFooter.test.tsx.snap
Labels: accessibility, area: front-end, type: bug

#2205 Update dark mode palette
  src/web/src/components/AdminButtons.tsx
  src/web/src/components/Posts/PostAvatar.tsx
  src/web/src/components/SearchBar.tsx
  src/web/src/theme/index.ts
Labels: area: front-end

#2206 Added CPU cores calculation for determining the number of concurrency workers
  .github/workflows/node-js-ci.yml
  .github/workflows/release.yml
Labels: area: CI/CD

#2208 Don't run unit tests on npm version
  package.json
Labels: area: deployment, developer experience
