Repository Seneca-CDOT/telescope, pull requests merged in 2021-10, with the labels that each got.

#2318 Closes #2210: Add node 16 to our CI build matrix
  .github/workflows/node-js-ci.yml
  .github/workflows/release.yml
  src/backend/data/feed.js
  test/feed.test.js
Labels: area: CI/CD, hacktoberfest-accepted

#2316 Close #2312: Better filtering of GitHub webooks by autodeployment server
  tools/autodeployment/webhook.js
Labels: type: enhancement, hacktoberfest-accepted, area: autodeployment

#2320 [Timeline]: Fix margin issue
  src/web/src/components/Posts/Timeline.tsx
Labels: area: front-end

#2323 Revert "Temporary fix for dev.to RSS bug forem/forem#11268"
  src/backend/utils/html/index.js
  src/backend/utils/html/remove-devto-fullscreen.js
  test/remove-devto-fullscreen.test.js
Labels: hacktoberfest-accepted

#2326 Fixes #2324: Cannot find module '../lib' from 'src/web/node_modules/react-icons/fa/index.js'
  src/web/package.json
Labels: type: bug, dependencies, hacktoberfest-accepted

#2327 Fixes #2212 Remove api:* scripts if not needed
  package.json
Labels: developer experience, area: tools, hacktoberfest-accepted

#2333 Closes #2329: Update react-icons to v4.3.1
  src/web/package.json
Labels: dependencies, hacktoberfest-accepted

#2335 Increase backoff attempts/delay before marking feed invalid
  config/env.production
  config/env.staging
Labels: area: back-end

#2410 Closes Issue #2374: Include more details about issues and pull requests
  src/web/src/components/Posts/Commits.tsx
  src/web/src/components/Posts/Issues.tsx
  src/web/src/components/Posts/PullRequests.tsx
Labels: area: front-end, hacktoberfest-accepted

#2337 escape thing inside of code tag
  src/backend/utils/html/index.js
  src/backend/utils/html/replace-entities.js
  src/backend/utils/html/syntax-highlight.js
  test/process-html.test.js
  test/replace-entities.test.js
Labels: hacktoberfest-accepted

#2408 Revert "Upgrade ESLint and eslint-related plugins to the lastest vers…
  package.json
Labels: type: bug, area: CI/CD, area: deployment, dependencies, hacktoberfest-accepted

#2422 Issue 1974: Student Quotes
  src/web/src/components/Banner.tsx
  src/web/src/student-quotes.js
Labels: area: front-end, hacktoberfest-accepted

#2400 Adding sugestions to install WSL2 and it packages in environment-setup.md
  docs/environment-setup.md
Labels: type: documentation (docs), hacktoberfest-accepted

#2396 Add a planet microservice
  config/env.development
  config/env.production
  config/env.staging
  config/nginx.conf.development.template
  config/nginx.conf.template
  docker/development.yml
  docker/docker-compose.yml
  docker/production.yml
  package.json
  src/api/planet/.dockerignore
  src/api/planet/Dockerfile
  src/api/planet/README.md
  src/api/planet/env.local
  src/api/planet/package.json
  src/api/planet/src/index.js
  src/api/planet/src/planet.js
  src/api/planet/src/server.js
  src/api/planet/static/feed-icon-10x10.png
  src/api/planet/static/planet-cdot-logo.png
  src/api/planet/static/planet.css
  src/api/planet/views/compare-planets.handlebars
  src/api/planet/views/layouts/LICENSE
  src/api/planet/views/layouts/main.handlebars
  src/api/planet/views/planet.handlebars
  src/api/posts/src/index.js
  src/api/posts/src/routes/feeds.js
  src/api/posts/src/validation.js
  src/backend/web/app.js
  src/backend/web/routes/index.js
Labels: hacktoberfest-accepted, area: microservices

#2425 chore: bump babel-jest to 27.3.1
  package.json
  src/api/feed-discovery/test/middleware.test.js
  src/api/feed-discovery/test/router.test.js
Labels: dependencies
