Repository Seneca-CDOT/telescope, pull requests merged in 2021-09, with the labels that each got.

#2293 chore: bump passport-saml to v3.1.2
  package.json
  src/api/auth/package.json
  test/jest.config.js
Labels: area: back-end, Priority: High, type: security, dependencies

#2295 Commented Sign up button as a bandaid solution
  src/web/src/components/BannerButtons.tsx
Labels: area: front-end

#2297 Closes #2160: Remove unused env variables
  config/env.production
  config/env.staging
Labels: area: microservices

#2298 fix: remove type errors to avoid crashing during build process
  src/web/src/components/AuthProvider.tsx
  src/web/src/components/SearchResults.tsx
Labels: area: front-end, Priority: High

#2319 Fix 2306: Allow embedded content from medium.com
  src/backend/utils/html/sanitize.js
  test/sanitize-html.test.js
Labels: area: back-end
