Repository Seneca-CDOT/telescope, pull requests merged in 2021-11, with the labels that each got.

#2428 Fix routes and CSP in status microservice
  config/env.development
  docker/development.yml
  docker/docker-compose.yml
  docker/production.yml
  src/api/status/env.local
  src/api/status/package.json
  src/api/status/public/index.html
  src/api/status/src/server.js
Labels: area: microservices

#2447 Fixes #2442: Fixes linking of users icon, and adds title to users and telescope avatar icons
  src/web/src/components/Posts/PostAvatar.tsx
  src/web/src/components/Posts/Users.tsx
  src/web/src/components/TelescopeAvatar.tsx
Labels: area: front-end, accessibility

#2467 Fixes #2465 fix prettier error in server.js file
  src/api/status/src/server.js
Labels: type: bug, area: CI/CD

#2474 add Gitpod doc
  .gitpod.yml
  docs/CONTRIBUTING.md
  docs/gitpod.md
  docs/images/gitpodVSCode.png
  docs/images/openInGitpod.png
Labels: type: documentation (docs)

#2398 Fixes #2382 SSH to AWS EC2 with Visual Studio Code for remote development
  docs/remote-development/aws-cloud9.md
  docs/remote-development/vscode-ssh.md
  tools/aws-ip.sh
Labels: type: documentation (docs), developer experience, area: deployment

#2468 Fix escape character
  package.json
  src/backend/utils/html/syntax-highlight.js
  test/process-html.test.js
  test/syntax-highlight.test.js
Labels: area: back-end

#2472 Closes #2433: Customize the dashboard so it looks like it belongs to Telescope
  src/api/status/public/css/site.css
  src/api/status/public/index.html
  src/api/status/public/style.css
Labels: area: front-end
