Repository Seneca-CDOT/telescope, pull requests merged in 2021-01, with the labels that each got.

#1537 Add Initial Project Diagram Drawing
  docs/images/initialProjectDiagram.jpeg
Labels: 5 min fix, type: documentation (docs), type: enhancement, type: nice to have

#1550 Fixed #1549: Modified _app and _document to ensure matching styling between client and server
  .eslintrc.js
  src/frontend/next/src/pages/_app.tsx
  src/frontend/next/src/pages/_document.tsx
Labels: area: nextjs

#1551 Ported SnackBar component
  src/frontend/next/package.json
  src/frontend/next/src/components/SnackBar/SnackBar.tsx
Labels: area: nextjs

#1552 Ported ScrollAction component
  src/frontend/next/src/components/ScrollAction/ScrollAction.tsx
Labels: area: nextjs

#1565 [1535] Updated docs to include initial project diagram
  docs/overview.md
Labels: type: documentation (docs), type: nice to have

#1531 [next] 1358 - MainPage (index.js)
  src/frontend/next/src/components/BackToTopButton.tsx
  src/frontend/next/src/components/Banner.tsx
  src/frontend/next/src/components/Posts.tsx
  src/frontend/next/src/pages/index.tsx
Labels: area: nextjs

#1567 Fix #1501 port context/User to nextJS
  src/frontend/next/src/components/UserProvider.tsx
  src/frontend/next/src/hooks/use-authorization.ts
  src/frontend/next/src/interfaces/index.ts
  src/frontend/next/src/pages/_app.tsx
Labels: area: nextjs

#1462 Port Spinner from Gatsby to Next.js(TS)
  src/frontend/next/src/components/Spinner.tsx
Labels: Priority: High, area: front-end, area: nextjs

#1564 Fix #1480 Port BackToTopButton from Gatsby to NextJS
  .eslintrc.js
  src/frontend/next/src/components/BackToTopButton.tsx
  src/frontend/next/src/components/ScrollAction.tsx
Labels: area: front-end, area: nextjs

#1573 [1227] Fixed Eslint warnings
  src/frontend/gatsby/src/components/Login/Login.jsx
  src/frontend/gatsby/src/components/Post/Post.jsx
  src/frontend/gatsby/src/components/Posts/LoadAutoScroll.jsx
  src/frontend/gatsby/src/components/Posts/Posts.jsx
Labels: area: back-end, area: front-end, developer experience, type: bug

#1575 [next] Fixes #1547: Ported HelpPopoverButton from Gatsby to Next.js
  src/frontend/next/package.json
  src/frontend/next/src/components/HelpPopoverButton.tsx
Labels: area: front-end, area: nextjs

#1562 [next] Item 2 and 4 related to /styles/global.css of Issue #1548
  src/frontend/next/src/styles/globals.css
  src/frontend/next/src/styles/telescope-post-content.css
Labels: area: nextjs

#1578 Fix #1507: Port SearchHelp from Gatsby to Nextjs
  src/frontend/next/src/components/SearchHelp.tsx
Labels: area: front-end, area: nextjs

#1577 [next] Fixes issue-1541: Ported AuthorSearchInput component to Next.JS
  src/frontend/next/src/components/SearchInput/AuthorSearchInput.tsx
Labels: area: front-end, area: nextjs

#1579 [next] Issue 1548 item 5: Install highlight.js and import highlight.js CSS to global css
  src/frontend/next/package.json
  src/frontend/next/src/styles/globals.css
Labels: area: nextjs

#1574 Providing Theme object to the whole app
  src/frontend/next/src/pages/_app.tsx
  src/frontend/next/src/theme/lightTheme.ts
Labels: area: nextjs

#1580 [next] Issue 1500 - Port SearchInput to NEXT.js
  src/frontend/next/src/components/SearchInput/SearchInput.tsx
Labels: area: nextjs

#1582 [next] Fixes #1539: Porting DeleteFeedDialogButton to Next
  src/frontend/next/src/components/DeleteFeedDialogButton.tsx
Labels: area: front-end, area: nextjs, type: enhancement

#1504 Fix #1459: Added Post and Posts to NextJS
  src/frontend/next/src/components/AdminButtons.tsx
  src/frontend/next/src/components/Posts/LoadAutoScroll.tsx
  src/frontend/next/src/components/Posts/Post.tsx
  src/frontend/next/src/components/Posts/Timeline.tsx
  src/frontend/next/src/components/Posts/index.tsx
  src/frontend/next/src/interfaces/index.ts
Labels: area: front-end, area: nextjs

#1587 Update README with Netlify badge for next.js builds
  README.md
Labels: area: CI/CD, developer experience

#1602 Fix #1597: [next] post banner has incorrect style
  src/frontend/next/src/components/Posts/Post.tsx
Labels: area: css styling, area: front-end, area: nextjs

#1594 Fixes #1593, added /out into .prettierignore
  .prettierignore
Labels: area: nextjs

#1569 Added more node versions to GH actions for testing
  .github/workflows/node-js-ci.yml
Labels: area: CI/CD

#1599 [next] Fixes: 1596 - ScrollToTop issues
  src/frontend/next/src/components/BackToTopButton.tsx
  src/frontend/next/src/theme/lightTheme.ts
Labels: area: nextjs

#1600 Add filter to avoid processing more than one POST requests in a release
  tools/autodeployment/server.js
Labels: area:deployment

#1613 [next] Fixes #1612 Ported BannerDynamicItems component from Gatsby to Next
  src/frontend/next/src/components/BannerDynamicItems.tsx
  src/frontend/next/src/components/DynamicImage.tsx
Labels: area: front-end, area: nextjs

#1614 Fixes: 1595 - [next] Infinite Scrolling of Posts is broken (All of our infinite scrolls were broken)
  src/frontend/gatsby/src/components/Posts/LoadAutoScroll.jsx
  src/frontend/next/src/components/Posts/LoadAutoScroll.tsx
Labels: Priority: High, area: nextjs

#1622 Fix #1620: useUser() should always return a valid User object
  src/frontend/next/src/components/UserProvider.tsx
  src/frontend/next/src/hooks/use-authorization.ts
Labels: area: nextjs

#1623 Allow proxying next's webpack dev server (add unsafe-eval CSP for script-src) via backend
  src/backend/web/app.js
Labels: area: back-end, area: nextjs, area: web server

#1624 [next] Fixes #1463 - re-re-implements the About page w/ nextjs
  src/frontend/next/next.config.js
  src/frontend/next/package.json
  src/frontend/next/src/pages/about.mdx
Labels: area: front-end, area: nextjs

#1619 fix #1494: Port adminbutton to [next]
  src/frontend/next/src/components/AdminButtons.tsx
Labels: area: nextjs

#1566 Fixed #1508: Ported SEO component to NextJS
  src/frontend/next/src/components/SEO.tsx
  src/frontend/next/src/config.ts
  src/frontend/next/src/pages/_document.tsx
Labels: Priority: High, area: nextjs
