Repository Seneca-CDOT/telescope, pull requests merged in 2021-02, with the labels that each got.

#1626 Closes #1604: Use octokit/webhooks.js in autodeployment server
  tools/autodeployment/package.json
  tools/autodeployment/server.js
Labels: Priority: Low, area:deployment

#1505 Fixed #1491: Port MyFeedsPage, see src/frontend/src/pages/myfeeds.js to NextJS
  src/frontend/next/package.json
  src/frontend/next/src/components/ExistingFeedList.tsx
  src/frontend/next/src/components/SnackBar.tsx
  src/frontend/next/src/pages/myfeeds.tsx
Labels: Priority: High, area: nextjs

#1625 [next] Fixes #1546: Ported SearchResults to NextJS and fixed styling on search error
  src/frontend/next/src/components/SearchResults.tsx
Labels: Priority: High, area: front-end, area: nextjs, type: enhancement

#1628 [CI/CD] Fixes #1301: Created automated release workflow
  .github/workflows/release.yml
  .npmrc
Labels: Priority: High, area: CI/CD, area: tools, developer experience, type: enhancement

#1637 Fixed#77: Added Dark theme
  src/frontend/next/src/components/Posts/Post.tsx
  src/frontend/next/src/components/Posts/index.tsx
  src/frontend/next/src/components/ThemeToggleButton.tsx
  src/frontend/next/src/pages/_app.tsx
  src/frontend/next/src/pages/_document.tsx
  src/frontend/next/src/pages/index.tsx
  src/frontend/next/src/styles/globals.css
  src/frontend/next/src/theme/index.ts
  src/frontend/next/src/theme/lightTheme.ts
Labels: area: css styling, area: front-end, area: nextjs

#1640 netlify: force rebuild with every merge to avoid 'failed' message in badge
  netlify.toml
Labels: area: CI/CD

#1648 [CI/CD] Fixes #1638: Configured npm version to run tests and push to upstream master
  package.json
Labels: Priority: High, area: CI/CD, area: tools, developer experience, type: enhancement

#1583 Port SearchPage from Gatsby to NextJS
  src/frontend/next/src/pages/search.tsx
Labels: Priority: High, area: front-end, area: nextjs

#1621 [next] Fixes #1484: Re-Adds the Search page component
  src/frontend/next/src/components/SearchPage.tsx
  src/frontend/next/src/pages/search.tsx
Labels: area: front-end, area: nextjs

#1654 Fixed#1652: Fixed theme toggle button disappear when there is error of loading posts
  src/frontend/next/src/components/Posts/index.tsx
Labels: area: css styling, type: bug

#1656 [next] Update react from 16 to 17 on nextjs
  src/frontend/next/package.json
Labels: area: nextjs

#1659 refactor(next): Fixed #1446 - Migrated headers to Next.js and TS
  src/frontend/next/src/components/Header/DesktopHeader.tsx
  src/frontend/next/src/components/Header/MobileHeader.tsx
  src/frontend/next/src/components/Header/index.tsx
  src/frontend/next/src/pages/_app.tsx
Labels: Priority: High, area: nextjs

#1665 feat: New Logo
  src/frontend/next/public/icons/apple-icon-180.png
  src/frontend/next/public/icons/apple-splash-1125-2436.jpg
  src/frontend/next/public/icons/apple-splash-1136-640.jpg
  src/frontend/next/public/icons/apple-splash-1170-2532.jpg
  src/frontend/next/public/icons/apple-splash-1242-2208.jpg
  src/frontend/next/public/icons/apple-splash-1242-2688.jpg
  src/frontend/next/public/icons/apple-splash-1284-2778.jpg
  src/frontend/next/public/icons/apple-splash-1334-750.jpg
  src/frontend/next/public/icons/apple-splash-1536-2048.jpg
  src/frontend/next/public/icons/apple-splash-1620-2160.jpg
  src/frontend/next/public/icons/apple-splash-1668-2224.jpg
  src/frontend/next/public/icons/apple-splash-1668-2388.jpg
  src/frontend/next/public/icons/apple-splash-1792-828.jpg
  src/frontend/next/public/icons/apple-splash-2048-1536.jpg
  src/frontend/next/public/icons/apple-splash-2048-2732.jpg
  src/frontend/next/public/icons/apple-splash-2160-1620.jpg
  src/frontend/next/public/icons/apple-splash-2208-1242.jpg
  src/frontend/next/public/icons/apple-splash-2224-1668.jpg
  src/frontend/next/public/icons/apple-splash-2388-1668.jpg
  src/frontend/next/public/icons/apple-splash-2436-1125.jpg
  src/frontend/next/public/icons/apple-splash-2532-1170.jpg
  src/frontend/next/public/icons/apple-splash-2688-1242.jpg
  src/frontend/next/public/icons/apple-splash-2732-2048.jpg
  src/frontend/next/public/icons/apple-splash-2778-1284.jpg
  src/frontend/next/public/icons/apple-splash-640-1136.jpg
  src/frontend/next/public/icons/apple-splash-750-1334.jpg
  src/frontend/next/public/icons/apple-splash-828-1792.jpg
  src/frontend/next/public/icons/manifest-icon-192.png
  src/frontend/next/public/icons/manifest-icon-512.png
  src/frontend/next/public/logo.svg
Labels: area: design, area: front-end, area: nextjs

#1669 Closes #1439: Fix eslint warnings from Gatsby build
  src/frontend/gatsby/src/components/MyFeedsPage/DeleteFeedDialogButton.jsx
Labels: area: front-end, developer experience

#1670 Fix unclickable logo in [next] desktop and mobile header
  src/frontend/next/src/components/Header/DesktopHeader.tsx
  src/frontend/next/src/components/Header/MobileHeader.tsx
Labels: area: front-end, area: nextjs

#1671 fix(linter): remove 'Prefer await to then()' rule
  .eslintrc.js
Labels: developer experience

#1673 Fixes: 1672 - [next] Investigate bugs related to Fonts.
  src/frontend/next/package.json
  src/frontend/next/src/pages/_app.tsx
Labels: area: front-end, area: nextjs, type: bug

#1685 Fixes #1684: Removed release-it from dependencies
  package.json
Labels: 5 min fix, area: CI/CD

#1650 [Documentation] Fixes #1632: Updated release documentation
  docs/release.md
Labels: Priority: Medium, developer experience, type: documentation (docs)

#1667 Porting Banner to Next [1616]
  src/frontend/next/src/components/Banner.tsx
  src/frontend/next/src/components/BannerDynamicItems.tsx
  src/frontend/next/src/components/DynamicImage.tsx
Labels: Priority: High, area: front-end, area: nextjs

#1694 Fixes #1534, Added Legacy Dependencies Check
  .npmrc
Labels: developer experience

#1700 Fixes #1376 - Add No-Results-Image to Next and Gatsby search results components
  src/frontend/gatsby/src/components/SearchPage/SearchResults.jsx
  src/frontend/gatsby/src/images/noResults.svg
  src/frontend/next/public/noResults.svg
  src/frontend/next/src/components/SearchResults.tsx
  src/frontend/src/images/NotFound.jpg
Labels: Priority: High, area: front-end, area: nextjs

#1698 [UI 2.0] Fixes1697 - New logo with a red dot
  src/frontend/next/public/logo-badged.svg
Labels: area: design, area: front-end, area: nextjs

#1699 Fixes #1686 [next] Update deprecated Fonts.
  src/frontend/next/package.json
  src/frontend/next/src/pages/_app.tsx
Labels: area: front-end, area: nextjs, type: bug

#1707 Fixes #1647: Created config file for Dependabot
  .github/dependabot.yml
Labels: Priority: Medium, area: tools, dependencies, developer experience, type: enhancement

#1692 Adjusted light theming color for UI 2.0
  src/frontend/next/src/theme/index.ts
Labels: area: design, area: front-end, area: nextjs

#1738 Fixes: #1734 - Height of navbar is wrong + Color Theme (back to old one) + remove BANNER from non-home pages
  src/frontend/next/src/components/Banner.tsx
  src/frontend/next/src/components/Header/DesktopHeader.tsx
  src/frontend/next/src/components/Header/MobileHeader.tsx
  src/frontend/next/src/components/Posts/Post.tsx
  src/frontend/next/src/pages/search.tsx
  src/frontend/next/src/theme/index.ts
Labels: area: front-end, area: nextjs, type: bug

#1703 Fixes #1663 - rewrote LoggedIn and LoggedOut components
  src/frontend/next/src/components/Login/LoggedIn.tsx
  src/frontend/next/src/components/Login/LoggedOut.tsx
  src/frontend/next/src/components/Login/index.tsx
Labels: area: front-end, area: nextjs

#1742 Fix #1420 - site crash when no post found
  src/frontend/next/src/components/SearchResults.tsx
Labels: area: front-end, area: nextjs, type: bug

#1701 Fixed issue #1682 - rewrote buttons to be clickable on the entire but…
  src/frontend/next/src/components/Header/DesktopHeader.tsx
  src/frontend/next/src/components/Header/MobileHeader.tsx
Labels: area: front-end, area: nextjs

#1741 Fix #1630 - triggering search via URL
  src/frontend/next/src/components/SearchPage.tsx
Labels: area: front-end, area: nextjs

#1749 chore: bump @next/mdx from 10.0.6 to 10.0.7 in src/frontend/next
  src/frontend/next/package.json
Labels: area: nextjs, dependencies

#1751 Add vercel.json see https://vercel.com/docs/configuration
  vercel.json
Labels: area: CI/CD, area:deployment, developer experience

#1752 chore: bump @types/node from 14.14.8 to 14.14.28 in src/frontend/next
  src/frontend/next/package.json
Labels: area: nextjs, dependencies

#1754 chore: bump @types/react from 16.9.51 to 17.0.2 in src/frontend/next
  src/frontend/next/package.json
Labels: area: nextjs, dependencies

#1756 chore: bump next version from 10.0.2 to 10.0.7 in src/frontend/next
  src/frontend/next/package.json
Labels: area: nextjs, dependencies

#1695 Fixes #1557: Initial Typescript and NextJS Documentation
  docs/front-end.md
  docs/theme-and-colours.md
Labels: area: nextjs, type: documentation (docs)

#1757 chore: bump react-material-ui-form-validator from 2.1.2 to 2.1.4
  src/frontend/next/package.json
Labels: area: nextjs, dependencies

#1758 chore: bump swr from 0.4.0 to 0.4.2 in src/frontend/next
  src/frontend/next/package.json
Labels: area: nextjs, dependencies

#1759 chore: bump typescript from 4.1.2 to 4.1.5 in src/frontend/next
  src/frontend/next/package.json
Labels: area: nextjs, dependencies

#1761 chore: bump @octokit/webhooks and date-fns
  tools/autodeployment/package.json
Labels: area: autodeployment, dependencies

#1760 chore: bump react-use from 15.3.8 to 17.1.1 in src/frontend/next
  src/frontend/next/package.json
Labels: area: nextjs, dependencies

#1763 chore: bump highlight.js from 10.4.1 to 10.6.0
  package.json
  test/syntax-highlight.test.js
Labels: dependencies

#1762 refactor(ci): refactored Dependabot configuration
  .github/dependabot.yml
Labels: Priority: Medium, area: tools, dependencies, developer experience, type: enhancement

#1768 Fix: issue 1588 - Update bull board and highlight.js dep
  package.json
  src/backend/feed/queue.js
  src/backend/web/routes/admin.js
Labels: dependencies

#1774 refactor(tidy up): Fixes #1655 - Removed unnecessary <Head>, <meta>, and <title> tags
  src/frontend/next/src/pages/_document.tsx
  src/frontend/next/src/pages/index.tsx
  src/frontend/next/src/pages/search.tsx
Labels: 5 min fix, area: front-end, area: nextjs

#1769 style(port): Fixes 1651 - Styles the About page
  src/frontend/next/src/markdown-pages/about.md
  src/frontend/next/src/pages/about.mdx
  src/frontend/next/src/pages/layouts/MDXPageBase.tsx
Labels: area: front-end

#1788 #1750 - fixed Login component display in Dark Mode
  src/frontend/next/src/components/Header/MobileHeader.tsx
  src/frontend/next/src/components/Login/LoggedIn.tsx
  src/frontend/next/src/components/Login/LoggedOut.tsx
Labels: area: nextjs, type: bug

#1785 fix:1784 - Post search input bug
  src/frontend/next/src/components/SearchInput/AuthorSearchInput.tsx
  src/frontend/next/src/components/SearchInput/PostSearchInput.tsx
Labels: Priority: High, area: front-end, area: nextjs, type: bug

#1787 Fixes #1189, Added Space Removal for Paragraphs
  package.json
  src/backend/utils/html/remove-empty-paragraphs.js
  test/remove-empty-paragraphs.test.js
Labels: area: back-end

#1783 Fixes: #1370 Set picture in post as their natural size
  src/frontend/next/src/styles/telescope-post-content.css
Labels: area: css styling, area: front-end, type: bug

#1798 chore: remove gatsby dependencies from telescope's Dockerfile
  Dockerfile
Labels: area: front-end, dependencies

#1813 Fix eslint and prettier for repo updates
  .eslintrc.js
  .prettierignore
Labels: area: CI/CD, developer experience

#1816 Temporary fix for dev.to RSS bug https://github.com/forem/forem/pull/11268
  src/backend/utils/html/index.js
  src/backend/utils/html/remove-devto-fullscreen.js
  test/remove-devto-fullscreen.test.js
Labels: area: back-end

#1821 UI 2.0 Sidebar 1687 and fix: 1823 Log Out button
  src/web/src/components/Header/DesktopHeader.tsx
  src/web/src/components/Header/MobileHeader.tsx
  src/web/src/components/Header/index.tsx
  src/web/src/components/Login/LoggedIn.tsx
  src/web/src/components/Login/LoggedOut.tsx
  src/web/src/components/Login/index.tsx
Labels: area: front-end, area: nextjs

#1824 Fix for DateTimeFormatOptions issue
  src/web/src/components/Posts/Post.tsx
Labels: area: front-end, area: nextjs

#1825 Update dependabot doc
  docs/dependabot.md
Labels: help wanted, type: documentation (docs)

#1827 Update eslintignore to use glob patterns for node_modules deep in repo
  .eslintignore
  package.json
Labels: developer experience

#1826 Always use src/api/env.development with npm services:* scripts
  tools/services.js
Labels: area: docker, developer experience

#1831 Added new changlelog generator
  .github/workflows/release.yml
  release-changelog-builder-config.json
Labels: Priority: High, area: CI/CD, area: tools, developer experience, type: bug

#1834 Fixes #1780 - make GitHub Contributor Card styling consistent
  src/web/src/components/GitHubContributorCard.tsx
  src/web/src/pages/layouts/MDXPageBase.tsx
Labels: area: css styling, area: front-end, area: nextjs

#1832 Changed searchPage background color [1808]
  src/web/src/components/SearchBar.tsx
  src/web/src/components/SearchPage.tsx
Labels: area: css styling, area: front-end, area: nextjs

#1836 Fixes #1795 - added trailing slash to next.config.js
  src/web/next.config.js
Labels: area: nextjs

#1842 [UI 2.0] Change header buttons' style and refactor code
  src/web/src/components/Header/DesktopHeader.tsx
  src/web/src/components/Header/HeaderButton.tsx
  src/web/src/components/Login/LoggedIn.tsx
  src/web/src/components/Login/LoggedOut.tsx
Labels: area: front-end

#1853 Fixes #1841 - Fetch all contributors and fix contribution count plural
  src/web/src/components/GitHubContributorCard.tsx
  src/web/src/hooks/use-telescope-contributor.ts
Labels: Priority: Medium, type: bug
