Repository Seneca-CDOT/telescope, pull requests merged in 2022-05, with the labels that each got.

#3573 Responsive SVG art, and removed tutorial
  src/web/docusaurus/src/components/HomepageFeatures.module.css
  src/web/docusaurus/src/pages/index.js
  src/web/docusaurus/src/pages/index.module.css
  src/web/docusaurus/static/img/home_page/mountains_1.svg
  src/web/docusaurus/static/img/home_page/mountains_2.svg
  src/web/docusaurus/static/img/home_page/planet_3.svg
  src/web/docusaurus/static/img/home_page/sky_4.svg
  src/web/docusaurus/static/img/home_page/telescope_0.svg
Labels: area: docusaurus

#3585 Add eslint to Planet service
  pnpm-lock.yaml
  src/api/planet/package.json
Labels: type: bug

#3586 chore: fix dependency issues
  pnpm-lock.yaml
  src/api/parser/package.json
  src/web/app/package.json
  src/web/docusaurus/package.json
Labels: dependencies

#3587 refactor: fix link to about page in NavBar and remove About page
  src/web/app/src/components/AboutFooter.test.tsx
  src/web/app/src/components/AboutFooter.tsx
  src/web/app/src/components/AboutPage.tsx
  src/web/app/src/components/NavBar/index.tsx
  src/web/app/src/components/__snapshots__/AboutFooter.test.tsx.snap
  src/web/app/src/pages/about.tsx
Labels: area: front-end

#3584 Redesign telescope react native app
  src/mobile/.env.development
  src/mobile/.eslintrc.js
  src/mobile/app.config.js
  src/mobile/package.json
  src/mobile/src/App.jsx
  src/mobile/src/assets/logo.png
  src/mobile/src/components/Banner/Banner.jsx
  src/mobile/src/components/Banner/BannerButtons.jsx
  src/mobile/src/components/Banner/BannerText.jsx
  src/mobile/src/components/Footer.jsx
  src/mobile/src/components/GitHubContributorCard.jsx
  src/mobile/src/components/HomeHeader.jsx
  src/mobile/src/components/LineSeparator.jsx
  src/mobile/src/components/Post/Pagination.jsx
  src/mobile/src/components/Post/PaginationButton.jsx
  src/mobile/src/components/Post/Post.jsx
  src/mobile/src/components/Post/Posts.jsx
  src/mobile/src/components/Post/index.jsx
  src/mobile/src/components/Post/styles/post.js
  src/mobile/src/components/PostCard.jsx
  src/mobile/src/components/QuoteCard.jsx
  src/mobile/src/components/Skeleton.jsx
  src/mobile/src/navigation/BottomNavbar.jsx
  src/mobile/src/navigation/Navigation.jsx
  src/mobile/src/screens/AboutScreen.jsx
  src/mobile/src/screens/HomeScreen.jsx
  src/mobile/src/screens/PostScreen.jsx
  src/mobile/src/student-quotes.js
  src/mobile/src/utils/createUrl.js
  src/mobile/src/utils/formatPublishedDate.js
  src/mobile/src/utils/getNameInitials.js
Labels: area: React Native

#3627 [React Native] Change default environment file
  src/mobile/app.config.js
Labels: type: bug
