Repository Seneca-CDOT/telescope, pull requests merged in 2022-04, with the labels that each got.

#3372 Use single env-file in deploy.sh, append secrets instead
  tools/autodeployment/deploy.sh
Labels: area: autodeployment

#3379 Fix nginx config for oauth2-proxy
  config/nginx.conf.template
  docker/production.yml
Labels: type: bug

#3376 Fix docusaurus broken links
  src/web/docusaurus/docs/api-services/api.md
  src/web/docusaurus/docs/getting-started/environment-setup.md
  src/web/docusaurus/docs/getting-started/vscode-ssh.md
  src/web/docusaurus/docs/tools-and-technologies/login.md
  src/web/docusaurus/docs/tools-and-technologies/pino.md
  src/web/docusaurus/docs/tools-and-technologies/renovate.md
  src/web/docusaurus/docusaurus.config.js
Labels: area: docusaurus

#3211 Issue 1912: Searchbar Redesign
  src/web/app/src/components/SearchBar.tsx
  src/web/app/src/components/SearchInput/SearchInput.tsx
  src/web/app/src/components/SearchResults.tsx
  src/web/app/src/theme/index.ts
Labels: area: elasticsearch, review: normal

#3346 Using supabase to share student quotes between Telescope web and mobi…
  docker/supabase/volumes/db/init/04-telescope-schema.sql
  src/mobile/.env.development
  src/mobile/app.config.js
  src/mobile/app.json
  src/mobile/package.json
  src/mobile/src/App.jsx
  src/mobile/src/api/supabase.js
  src/mobile/src/components/Banner/Banner.jsx
  src/mobile/src/components/Banner/BannerText.jsx
  src/mobile/src/student-quotes.js
Labels: area: React Native

#3409 Add docusaurus healthcheck
  src/api/status/src/services.js
Labels: 5 min fix, area: dashboard, review: easy

#3429 Issue 3428: Search by Title in Advanced Search
  src/web/app/src/components/SearchBar.tsx
  src/web/app/src/components/SearchResults.tsx
Labels: review: easy

#3432 Searchbar on Enter
  src/web/app/src/components/SearchBar.tsx
  src/web/app/src/components/SearchInput/SearchInput.tsx
Labels: area: front-end, area: elasticsearch, review: easy

#3439 Fix docker legacy backend
  Dockerfile
Labels: type: bug

#3307 Refactor Dockerfile sso
  package.json
  pnpm-lock.yaml
  src/api/sso/.dockerignore
  src/api/sso/Dockerfile
Labels: area: docker, type: test, dependencies

#3461 Add missing server-token to ci workflows
  .github/workflows/docs-ci.yml
  .github/workflows/mobile-deploy.yml
Labels: area: CI/CD

#3363 Remove wiki-feed-parser, add logic to get feeds from supabase
  docker/development.yml
  docker/docker-compose.yml
  pnpm-lock.yaml
  src/api/parser/env.local
  src/api/parser/package.json
  src/api/parser/src/parser.js
  src/api/parser/src/utils/supabase.js
  src/api/parser/src/utils/wiki-feed-parser.js
  src/api/parser/test/e2e/parser-flow.test.js
  src/api/parser/test/wiki-feed-parser.test.js
Labels: area: microservices

#3480 Resolves #3293: Posts Service Documentation
  src/web/docusaurus/docs/api-services/posts.md
Labels: type: documentation (docs), area: docusaurus

#3475 Migrate https://github.com/Seneca-CDOT/telescope/wiki/Database-Maintenance to docs
  src/web/docusaurus/docs/contributing/database-maintenance.md
Labels: type: documentation (docs)

#3496 Add issuesURL field in /projects/:namespace/:name? route
  src/api/dependency-discovery/src/dependency-list.js
  src/api/dependency-discovery/src/github.js
  src/api/dependency-discovery/test/dependency.test.js
Labels: area: back-end, area: dependency visualization

#3490 Add unit tests to indexer.js in Parser
  src/api/parser/test/indexer.test.js
Labels: type: test, area: elasticsearch

#3498 Do not drop DB when restoring from backup
  docker/supabase/backup/restore-backup.sh
Labels: 5 min fix

#3502 Add Telescope Supabase docs
  src/web/docusaurus/docs/tools-and-technologies/supabase.md
  src/web/docusaurus/static/img/supabase-architecture.png
  src/web/docusaurus/static/img/supabase-studio.png
Labels: type: documentation (docs), area: supabase

#3503 Add Telescope Prisma docs
  src/web/docusaurus/docs/tools-and-technologies/prisma.md
Labels: type: documentation (docs)

#3488 Refactor feed-discovery, sso to handle blog, youtube, twitch URLs
  config/env.development
  config/env.production
  config/env.staging
  docker/docker-compose.yml
  src/api/feed-discovery/README.md
  src/api/feed-discovery/src/middleware.js
  src/api/feed-discovery/src/router.js
  src/api/feed-discovery/src/util.js
  src/api/feed-discovery/test/middleware.test.js
  src/api/feed-discovery/test/router.test.js
  src/api/feed-discovery/test/util.test.js
  src/api/sso/src/middleware.js
  src/api/sso/test/e2e/signup-flow.test.js
  src/web/app/src/components/SignUp/Forms/RSSFeeds.tsx
Labels: area: sso, area: microservices

#3499 Fix Search label text cut off
  src/web/app/src/components/SearchInput/SearchInput.tsx
Labels: 5 min fix, area: css styling

#3512 Fix image flickering on star field
  src/web/app/src/components/StarField.tsx
Labels: review: easy

#3515 Resize stars depending on screen width
  src/web/app/src/components/StarField.tsx
Labels: review: easy

#3513 Refactor copy button
  src/web/app/src/components/Posts/CopyButton.tsx
  src/web/app/src/components/Posts/ShareButton.tsx
  src/web/app/src/components/Posts/Timeline.tsx
Labels: review: easy

#3520 Adapt star field to docusaurus
  pnpm-lock.yaml
  src/web/docusaurus/docs/overview.md
  src/web/docusaurus/package.json
  src/web/docusaurus/src/components/StarField.jsx
  src/web/docusaurus/src/components/StarField.module.css
Labels: review: easy

#3521 Import p5.js dynamically on docs
  src/web/docusaurus/src/components/StarField.jsx
Labels: Priority: High

#3511 Remove TIMING=1 from lint. Add separate lint-time command
  package.json
  src/api/dependency-discovery/package.json
  src/api/feed-discovery/package.json
  src/api/image/package.json
  src/api/parser/package.json
  src/api/planet/package.json
  src/api/posts/package.json
  src/api/search/package.json
  src/api/sso/package.json
  src/api/status/package.json
  src/github-url-parser/package.json
  src/mobile/package.json
  src/satellite/package.json
  src/web/app/package.json
  src/web/docusaurus/package.json
  turbo.json
Labels: review: easy

#3522 Remove showLastUpdate in Docusaurus
  src/web/docusaurus/docusaurus.config.js
Labels: type: test, review: easy

#3485 Replaced `octokit/request` with `octokit/octokit` in dependency-discovery
  pnpm-lock.yaml
  src/api/dependency-discovery/package.json
  src/api/dependency-discovery/src/github.js
  src/api/status/package.json
  src/api/status/src/js/octokit.js
Labels: review: unknown

#3487 Add UI for dependency discovery
  docker/development.yml
  docker/docker-compose.yml
  docker/production.yml
  src/web/Dockerfile
  src/web/app/next.config.js
  src/web/app/src/components/BannerButtons.tsx
  src/web/app/src/components/DependenciesPage.tsx
  src/web/app/src/components/DependenciesTable/Row.tsx
  src/web/app/src/components/DependenciesTable/index.tsx
  src/web/app/src/components/NavBar/index.tsx
  src/web/app/src/config.ts
  src/web/app/src/pages/dependencies.tsx
Labels: area: front-end, area: dependency visualization, review: normal

#3539 Add --team flag to turborepo command
  .github/workflows/eslint-ci.yml
  .github/workflows/unit-tests-ci.yml
Labels: review: easy

#3538 Changing About us navigation and update our Docusaurus about us
  src/web/app/src/components/AboutPage.tsx
  src/web/app/src/components/BannerButtons.tsx
  src/web/docusaurus/docs/overview.md
Labels: type: documentation (docs), area: docusaurus

#3543 Status service documentation
  src/web/docusaurus/docs/api-services/status.md
Labels: type: documentation (docs), area: microservices, review: easy

#3542 Add docs for dependency-discovery
  src/web/docusaurus/docs/api-services/dependency-discovery.md
Labels: type: documentation (docs), area: microservices, review: normal

#3529 Update Feed in parser service to talk to Supabase instead of Redis
  docker/development.yml
  src/api/parser/env.local
  src/api/parser/src/data/feed.js
  src/api/parser/src/index.js
  src/api/parser/src/parser.js
  src/api/parser/src/utils/__mocks__/supabase.js
  src/api/parser/src/utils/storage.js
  src/api/parser/src/utils/supabase.js
  src/api/parser/test/e2e/parser-flow.test.js
  src/api/parser/test/feed-processor.test.js
  src/api/parser/test/feed.test.js
  src/api/parser/test/post.test.js
  src/api/parser/test/storage.test.js
Labels: area: redis, Priority: High, area: microservices, area: supabase, review: hard

#3486 [Can be shipped] Docusaurus home page
  src/web/docusaurus/src/components/HomepageFeatures.js
  src/web/docusaurus/src/components/HomepageFeatures.module.css
  src/web/docusaurus/static/img/home_page/mountains_1.svg
  src/web/docusaurus/static/img/home_page/mountains_2.svg
  src/web/docusaurus/static/img/home_page/planet_3.svg
  src/web/docusaurus/static/img/home_page/sky_4.svg
  src/web/docusaurus/static/img/home_page/telescope_0.svg
Labels: Priority: Medium, area: docusaurus, review: easy

#3523 SSO service documentation
  src/web/docusaurus/docs/api-services/auth.md
Labels: type: documentation (docs), area: sso, review: normal

#3554 Add production image tag
  src/web/docusaurus/docs/contributing/database-maintenance.md
Labels: review: easy
