Repository Seneca-CDOT/telescope, pull requests merged in 2022-10, with the labels that each got.

#3662 Closes #3653: Bump docusaurus to the release 2.1.0 and fix dependency issues
  pnpm-lock.yaml
  src/web/docusaurus/.eslintrc.js
  src/web/docusaurus/docusaurus.config.js
  src/web/docusaurus/package.json
Labels: dependencies, hacktoberfest-accepted

#3663 Get correct display_name for feeds
  src/api/parser/src/utils/supabase.js
Labels: hacktoberfest-accepted

#3668 Closes #3182, #3635: highlight.js reports unescaped HTML
  src/api/parser/src/utils/html/syntax-highlight.js
Labels: area: back-end, hacktoberfest-accepted

#3667 Fixes #3658: About Us button in all environments redirect to the Docusaurus site in staging
  src/web/app/src/components/BannerButtons.tsx
Labels: area: front-end, hacktoberfest-accepted

#3672 Fixes #3671 updates `pnpm dev` script in root
  package.json
Labels: hacktoberfest-accepted

#3673 [fix] Remove workspace-root option from pnpm list so more dependency info is collected
  src/api/dependency-discovery/deps.txt
  tools/collect-dependencies.js
Labels: hacktoberfest-accepted, area: dependency visualization

#3674 Link to Telescope documentation fix
  src/web/docusaurus/docusaurus.config.js
Labels: type: bug, hacktoberfest-accepted, area: docusaurus

#3681 Patch bump to next.js frontend deps
  pnpm-lock.yaml
  src/web/app/package.json
Labels: area: front-end, area: nextjs, hacktoberfest-accepted

#3679 Add parsing for missing title given as [Object]
  src/api/parser/src/data/post.js
Labels: type: bug, hacktoberfest-accepted

#3678 Link to Telescope documentation bug fix
  src/web/docusaurus/docusaurus.config.js
Labels: hacktoberfest-accepted, area: docusaurus

#3676 Update Satellite ES to 8.4.0, ES-mock to 2.0.0
  pnpm-lock.yaml
  src/satellite/package.json
  src/satellite/test.js
Labels: area: elasticsearch, hacktoberfest-accepted

#3682 Satellite release 1.28.0
  src/satellite/package.json
Labels: hacktoberfest-accepted

#3684 Update ElasticSearch 8.4.0
  docker/docker-compose.yml
  pnpm-lock.yaml
  src/api/dependency-discovery/package.json
  src/api/feed-discovery/package.json
  src/api/image/package.json
  src/api/parser/package.json
  src/api/parser/src/utils/indexer.js
  src/api/parser/test/indexer.test.js
  src/api/planet/package.json
  src/api/posts/package.json
  src/api/search/package.json
  src/api/search/src/search.js
  src/api/sso/package.json
  src/api/status/package.json
  tools/autodeployment/package.json
  tools/migrate/package.json
Labels: area: elasticsearch, hacktoberfest-accepted

#3691 Fixes #3614 by adding marginTop prop
  src/web/app/src/components/BannerButtons.tsx
Labels: hacktoberfest-accepted

#3694 Refactor- remove unused `search()` from `indexer`
  src/api/parser/src/utils/indexer.js
  src/api/parser/test/feed.test.js
  src/api/parser/test/indexer.test.js
Labels: hacktoberfest-accepted

#3695 #3671 update pnpm dev script in root with pnpm --filter
  package.json
Labels: hacktoberfest-accepted

#3696 chore: upgrade traefik image to v2.9.1
  docker/docker-compose.yml
Labels: hacktoberfest-accepted, area: traefik

#3701 Added Ukrainian translation for About page
  src/web/docusaurus/docusaurus.config.js
  src/web/docusaurus/i18n/uk/docusaurus-plugin-content-docs/current/overview.md
Labels: hacktoberfest-accepted, type: translation

#3703 Fixes #3565: Post user avatar not using proper GitHub image
  src/api/parser/src/data/feed.js
  src/api/parser/src/utils/storage.js
  src/api/parser/src/utils/supabase.js
  src/api/parser/test/feed.test.js
  src/api/posts/src/data/feed.js
  src/api/posts/src/storage.js
  src/web/app/src/components/Posts/Post.tsx
  src/web/app/src/components/Posts/PostAvatar.tsx
  src/web/app/src/components/Posts/PostInfo.tsx
  src/web/app/src/components/SignUp/Forms/GitHubAccount.tsx
  src/web/app/src/components/SignUp/Forms/Review.tsx
  src/web/app/src/interfaces/index.ts
Labels: hacktoberfest-accepted

#3693 [Issue-3666] Add PWA to docusaurus
  pnpm-lock.yaml
  src/web/docusaurus/.eslintrc.js
  src/web/docusaurus/docusaurus.config.js
  src/web/docusaurus/package.json
  src/web/docusaurus/pwaCustomButton.js
  src/web/docusaurus/static/img/manifest-icon-192.png
  src/web/docusaurus/static/img/manifest-icon-512.png
  src/web/docusaurus/static/manifest.json
Labels: hacktoberfest-accepted, area: docusaurus

#3707 chore: fix dependencies
  pnpm-lock.yaml
Labels: dependencies, hacktoberfest-accepted

#3709 Fixes #3650 add @babel/runtime dep to next.js frontend
  pnpm-lock.yaml
  src/web/app/package.json
Labels: area: front-end, hacktoberfest-accepted

#3706 Update `pnpm clean` script to include root directory and missing packages
  package.json
  pnpm-lock.yaml
  src/api/dependency-discovery/package.json
  src/api/feed-discovery/package.json
  src/api/image/package.json
  src/api/parser/package.json
  src/api/planet/package.json
  src/api/posts/package.json
  src/api/search/package.json
  src/api/sso/package.json
  src/api/status/package.json
  src/db/package.json
  src/github-url-parser/package.json
  src/satellite/package.json
  src/web/app/package.json
  src/web/docusaurus/package.json
  tools/autodeployment/package.json
  tools/eslint/package.json
  tools/migrate/package.json
Labels: hacktoberfest-accepted

#3698 Fixes #3686 Adding Mandarin(traditional Chinese) translation to About US page
  src/web/docusaurus/docusaurus.config.js
  src/web/docusaurus/i18n/zh/docusaurus-plugin-content-docs/current/overview.md
Labels: hacktoberfest-accepted, type: translation

#3718 Fixes #3717 update engine to node.js 16 and deps for status service
  pnpm-lock.yaml
  src/api/status/package.json
Labels: hacktoberfest-accepted, area: dashboard

#3723 Downgrade xterm dep as a bandaid fix for status dashboard build
  pnpm-lock.yaml
  src/api/status/package.json
Labels: dependencies, hacktoberfest-accepted, area: dashboard

#3726 Fixes #3713 update engine to node.js 16 and deps for planet service
  pnpm-lock.yaml
  src/api/planet/package.json
Labels: hacktoberfest-accepted, area: microservices

#3728 Fixes #3727 update engine to node.js 16 and deps for satellite service
  pnpm-lock.yaml
  src/satellite/package.json
Labels: hacktoberfest-accepted, area: microservices, area: satellite

#3729 Fixes #3712 update engine to node.js 16 and deps for image service
  pnpm-lock.yaml
  src/api/image/package.json
Labels: hacktoberfest-accepted, area: microservices

#3730 chore: upgrade satellite to v1.29.0
  src/satellite/package.json
Labels: hacktoberfest-accepted, area: microservices, area: satellite

#3733 chore: update moment.js
  src/mobile/package.json
Labels: dependencies

#3736 chore: update satellite to v.1.29.0 in all telescope services
  pnpm-lock.yaml
  src/api/dependency-discovery/package.json
  src/api/feed-discovery/package.json
  src/api/image/package.json
  src/api/parser/package.json
  src/api/planet/package.json
  src/api/posts/package.json
  src/api/search/package.json
  src/api/sso/package.json
  src/api/status/package.json
  tools/autodeployment/package.json
  tools/migrate/package.json
Labels: dependencies, hacktoberfest-accepted, area: microservices, area: satellite

#3741 3711: Upgraded node in feed discovery from v12 to 16
  src/api/feed-discovery/package.json
Labels: dependencies, hacktoberfest-accepted, area: microservices

#3722 Fixes #3692 by adding database info to `environment-setup` file
  src/web/docusaurus/docs/getting-started/environment-setup.md
Labels: type: documentation (docs), type: nice to have, hacktoberfest-accepted

#3742 Fixes #3715 update engine to node.js 16 and deps for search service
  pnpm-lock.yaml
  src/api/search/package.json
Labels: dependencies, hacktoberfest-accepted, area: microservices

#3743 Fixes #3611: Make RSS on Sign-up review page into snippets with hover display
  src/web/app/src/components/SignUp/Forms/Review.tsx
Labels: hacktoberfest-accepted

#3702 Improve Dependency Page CSS
  src/web/app/src/components/DependenciesTable/Row.tsx
Labels: hacktoberfest-accepted

#3748 Fixes #3716 update engine to node.js 16 and deps for sso service
  pnpm-lock.yaml
  src/api/sso/package.json
Labels: dependencies, hacktoberfest-accepted, area: microservices
