Repository Seneca-CDOT/telescope, pull requests merged in 2022-03, with the labels that each got.

#3085 Remove unnecessary graphs in dashboard
  src/api/status/public/assets/js/demo-chart.cjs
  src/api/status/public/assets/js/material-dashboard.cjs
  src/api/status/public/js/pages/dashboard.js
  src/api/status/public/js/pages/main.js
  src/api/status/src/views/status.hbs
Labels: 5 min fix, area: dashboard

#3093 Remove firebase.json file from config
  config/firebase.json
Labels: type: bug

#3100 Add Renovatebot badge
  README.md
Labels: 5 min fix, review: easy

#3113 Fixes #3107 Set Renovate bot to ignore `src/mobile` directory
  .github/renovate.json
Labels: area: React Native

#3128 Fixes #3125 add `clean` scripts to delete node_modules and build outputs
  package.json
  src/api/image/package.json
  src/api/status/package.json
  src/docs/package.json
  src/web/package.json
  turbo.json
Labels: developer experience, review: easy

#3110 Reconfig ESlint for dashboard sub-project
  pnpm-lock.yaml
  src/api/status/.eslintrc.js
  src/api/status/package.json
  tools/eslint/index.js
Labels: dependencies, review: easy

#3061 Use AWS for Ephemeral Dev Environments
  .vscode/extensions.json
  src/docs/docs/getting-started/vscode-ssh.md
  src/docs/static/img/aws_academy_start_lab.png
  src/docs/static/img/aws_console_region.png
  src/docs/static/img/aws_credentials.png
  src/docs/static/img/aws_elastic_ip_address.png
  src/docs/static/img/aws_elastic_ip_address_2.png
  src/docs/static/img/aws_elastic_ip_address_3.png
  src/docs/static/img/aws_elastic_ip_address_4.png
  src/docs/static/img/aws_iam_role.png
  src/docs/static/img/aws_instance_type.png
  src/docs/static/img/aws_key_pair.png
  src/docs/static/img/aws_linux_2_ami.png
  src/docs/static/img/aws_search_ec2.png
  src/docs/static/img/aws_ssh_config.png
  src/docs/static/img/aws_storage.png
  src/docs/static/img/aws_userdata.png
  tools/aws-ip.sh
  tools/aws-userdata.sh
Labels: type: documentation (docs), area: CI/CD, developer experience, area: tools

#3129 Opt-out of appendonly mode in redis
  docker/docker-compose.yml
Labels: type: bug, area: redis

#3138 [Fix]: Use proper way to require express-handlebars
  src/api/planet/src/index.js
Labels: dependencies

#3133 import Fragment from react
  src/docs/docs/tools-and-technologies/nextjs.md
Labels: 5 min fix, area: nextjs, review: easy

#3134 Reconfig Eslint for test sub-project
  test/.eslintrc.js
  tools/eslint/index.js
Labels: dependencies

#3146 Write feed-discovery documentation
  src/docs/docs/api-services/api.md
  src/docs/docs/api-services/auth.md
  src/docs/docs/api-services/feed-discovery.md
Labels: type: documentation (docs), review: easy

#3150 Setup Mermaid for Docusaurus
  pnpm-lock.yaml
  src/docs/docusaurus.config.js
  src/docs/package.json
Labels: accessibility, area: docusaurus, review: easy

#3101 Update docs for autodeployment routes
  tools/autodeployment/README.md
Labels: type: documentation (docs), area: web server, 5 min fix, area: autodeployment

#3165 Add sitemap to Docusaurus
  src/docs/docusaurus.config.js
Labels: area: docusaurus

#3172 Change eslint-config-telescope dependency from local to registry
  pnpm-lock.yaml
  src/api/dependency-discovery/package.json
Labels: good first issue, 5 min fix, satellite, review: easy

#3170 Adding usefull Expo CLI in react-native.md
  src/docs/docs/tools-and-technologies/react-native.md
Labels: type: documentation (docs), area: React Native

#3147 Vietnamese translation for the About page
  src/docs/docusaurus.config.js
  src/docs/i18n/vi/docusaurus-plugin-content-docs/current/overview.md
Labels: polyglot

#3173 Ignore img tag when using linkifier
  src/api/parser/src/data/post.js
  src/web/src/components/Posts/Post.tsx
Labels: area: front-end, 5 min fix, area: performance, review: easy

#3185 Use docker.cdot.systems image for feed-discovery in production
  docker/production.yml
Labels: area: docker

#3178 Integrate Satellite tests with jest config
  jest.config.base.js
  jest.config.js
  pnpm-lock.yaml
  src/api/dependency-discovery/jest.config.js
  src/api/dependency-discovery/jest.setup.js
  src/api/feed-discovery/jest.config.js
  src/api/parser/jest.config.js
  src/api/posts/jest.config.js
  src/satellite/jest.config.js
  src/web/jest.config.js
  test/jest.config.js
Labels: type: test

#3202 Fixes #3201 add feed-discovery image to gitpod.yml
  docker/gitpod.yml
Labels: type: documentation (docs), area: docker, area: deployment

#3219 Set up buildx before running containers in e2e tests for caching
  .github/workflows/e2e-tests-ci.yml
Labels: area: CI/CD, area: docker

#3210 Set up ESLint for image service
  pnpm-lock.yaml
  src/api/image/.eslintrc.js
  src/api/image/package.json
Labels: dependencies

#3186 Use `replace` instead of `replaceAll`
  tools/collect-dependencies.js
Labels: Priority: High, area: dependency visualization, review: easy

#3223 Switch deploy webhook URL to deal with redirects
  .github/workflows/continuous-delivery.yml
  .github/workflows/release.yml
Labels: area: CI/CD, area: autodeployment

#3233 Fixes #3212: Banner image failed to load because CORS violation
  src/api/image/src/index.js
Labels: area: front-end

#3250 Update @senecacdot/eslint-config-telescope to v1.0.1
  tools/eslint/package.json
Labels: dependencies

#3248 Wait on postgres to become ready before running sso e2e tests
  docker/supabase/docker-compose.yml
  pnpm-lock.yaml
  src/api/sso/jest.config.e2e.js
  src/api/sso/package.json
Labels: area: CI/CD, area: docker, type: test

#3239 Refactor Dockerfile status
  src/api/status/.dockerignore
  src/api/status/Dockerfile
Labels: area: docker

#3246 add TIMING=1 to eslint scripts
  package.json
  src/api/dependency-discovery/package.json
  src/api/image/package.json
  src/api/status/package.json
  src/docs/package.json
  src/mobile/package.json
  src/satellite/package.json
  src/web/package.json
Labels: area: back-end, area: front-end, type: nice to have, satellite, area: dashboard, area: dependency visualization, area: docusaurus

#3209 Fixes #3208 add auto-install-peers, install missing deps in src/web
  .npmrc
  pnpm-lock.yaml
  src/web/package.json
Labels: area: front-end, type: nice to have, dependencies

#3249 Add dependencies for MUI v5
  pnpm-lock.yaml
  src/web/package.json
Labels: area: front-end, dependencies

#3256 Refactor Dockerfile feed-discovery
  src/api/feed-discovery/.dockerignore
  src/api/feed-discovery/Dockerfile
Labels: area: docker

#3167 About page and fixing some ESLint problems by import react package
  src/mobile/package.json
  src/mobile/src/App.jsx
  src/mobile/src/components/Banner/Banner.jsx
  src/mobile/src/navigation/Navigation.jsx
  src/mobile/src/screens/AboutScreen.jsx
Labels: type: enhancement, area: React Native, review: easy

#3255 Refactor Dockerfile posts
  src/api/posts/.dockerignore
  src/api/posts/Dockerfile
Labels: area: docker

#3231 Refactor dependency-discovery dockerfile
  src/api/dependency-discovery/.dockerignore
  src/api/dependency-discovery/Dockerfile
Labels: area: docker

#3235 Refactor Dockerfile planet
  src/api/planet/.dockerignore
  src/api/planet/Dockerfile
Labels: area: docker

#3236 Refactor Dockerfile image
  src/api/image/.dockerignore
  src/api/image/Dockerfile
Labels: area: docker

#3238 Refactor Dockerfile search
  src/api/search/.dockerignore
  src/api/search/Dockerfile
Labels: area: docker

#3257 Fixes #3208 install missing deps in src/docs
  pnpm-lock.yaml
  src/docs/package.json
Labels: type: nice to have, dependencies, area: docusaurus

#3254 Use BuildKit with all Docker build commands for cache
  .github/workflows/e2e-tests-ci.yml
  bin/services-pull.js
  docker/docker-compose.yml
  docker/supabase/docker-compose.yml
  package.json
  src/docs/docs/api-services/api.md
  tools/services.js
Labels: area: CI/CD, area: docker, developer experience

#3269 Set up ESLint for post service
  pnpm-lock.yaml
  src/api/posts/.eslintrc.js
  src/api/posts/package.json
Labels: dependencies

#3265 Migrating to use docker.cdot.systems based images
  config/env.production
  config/env.staging
  docker/development.yml
  docker/docker-compose.yml
  docker/production.yml
Labels: area: docker

#3271 Set up ESLint for parser service.
  pnpm-lock.yaml
  src/api/parser/.eslintrc.js
  src/api/parser/package.json
  src/api/parser/src/utils/html/sanitize.js
  src/api/parser/src/utils/wiki-feed-parser.js
Labels: dependencies

#3284 Fixes #3208 install missing peer deps in root
  package.json
  pnpm-lock.yaml
Labels: dependencies

#3280 Remove custom healthcheck of status service
  docker/docker-compose.yml
  pnpm-lock.yaml
  src/api/status/package.json
  src/api/status/src/server.js
  src/web/Dockerfile
  src/web/next.config.js
  src/web/src/components/Banner.tsx
  src/web/src/config.ts
Labels: type: bug, approved

#3149 Add star field with GitHub contributors
  pnpm-lock.yaml
  src/web/package.json
  src/web/src/components/AboutPage.tsx
  src/web/src/components/StarField.tsx
Labels: area: front-end, rebase

#3292 Add more containers to E2e ci
  .github/workflows/e2e-tests-ci.yml
Labels: area: docker

#3298 Setup Eslint for Planet
  pnpm-lock.yaml
  src/api/planet/.eslintrc.js
  src/api/planet/package.json
Labels: dependencies

#3285 Updating autodeployment webhook to use custom "deploy" tag
  tools/autodeployment/webhook.js
Labels: type: enhancement, area: CI/CD, area: autodeployment

#3296 Setup Eslint for search
  pnpm-lock.yaml
  src/api/search/.eslintrc.js
  src/api/search/package.json
Labels: dependencies

#3316 Fixes #3213: Add .ts and .tsx to prettier script in root package.json
  package.json
Labels: developer experience

#3302 Dockerize Parser service
  docker/development.yml
  docker/docker-compose.yml
  docker/gitpod.yml
  docker/production.yml
  src/api/parser/Dockerfile
Labels: area: docker, area: microservices

#3309 Refactor Dockerfile docs
  src/docs/.dockerignore
  src/docs/Dockerfile
Labels: area: docker, approved

#3295 Get GitHub issues from dependency repo
  pnpm-lock.yaml
  src/api/dependency-discovery/package.json
  src/api/dependency-discovery/src/dependency-list.js
  src/api/dependency-discovery/src/github.js
  src/api/dependency-discovery/src/router.js
Labels: area: dependency visualization

#3334 Include github.sha for GIT_COMMIT in build args for CD
  .github/workflows/docker-build-and-push.yml
Labels: area: CI/CD

#3341 Fix: display buid status and total duration
  src/api/status/public/js/build-log/build-header.js
Labels: area: dashboard

#3361 docker-compose for Supabase in dev/prod
  config/env.development
  config/env.production
  config/env.staging
  docker/supabase/docker-compose.yml
  docker/supabase/supabase-development.yml
  docker/supabase/supabase-production.yml
Labels: area: docker, area: supabase
