Repository Seneca-CDOT/telescope, pull requests merged in 2022-11, with the labels that each got.

#3752 Issue 3747: Fixed all links use purple, even if not visited
  src/web/app/src/theme/index.ts
Labels: type: bug, area: front-end, hacktoberfest-accepted, area: accessibility

#3735 Fixes #3734: Improve google Lighthouse accessibly score #3734
  src/web/app/src/components/Posts/index.tsx
  src/web/app/src/theme/index.ts
Labels: area: front-end, area: performance, area: nextjs, hacktoberfest-accepted, area: microservices, area: accessibility

#3751 Auto select feed if only one exists
  src/web/app/src/components/SignUp/Forms/RSSFeeds.tsx
Labels: area: front-end

#3754 change font and font size of list item
  src/web/app/src/components/SearchHelp.tsx
Labels: area: front-end

#3757 Fixes #3755 :Base blogRss class's max-width to a parent element
  src/web/app/src/components/SignUp/Forms/Review.tsx
Labels: area: front-end

#3765 Added Russian translation of the overview docs page
  src/web/docusaurus/docusaurus.config.js
  src/web/docusaurus/i18n/ru/docusaurus-plugin-content-docs/current/overview.md
Labels: area: docusaurus, type: translation

#3762 Update environment-setup.md
  src/web/docusaurus/docs/getting-started/environment-setup.md
  src/web/docusaurus/static/img/dockerDesktopExample.png
Labels: type: documentation (docs), developer experience

#3761 Replace ThemeToggleButton with ThemeSelector
  src/web/app/public/colorThemes/dark-default.png
  src/web/app/public/colorThemes/dark-dim.png
  src/web/app/public/colorThemes/light-default.png
  src/web/app/public/colorThemes/light-high-contrast.png
  src/web/app/src/components/NavBar/index.tsx
  src/web/app/src/components/ThemeProvider.tsx
  src/web/app/src/components/ThemeSelector.tsx
  src/web/app/src/components/ThemeToggleButton.tsx
  src/web/app/src/hooks/use-preferred-theme.ts
  src/web/app/src/interfaces/index.ts
  src/web/app/src/pages/_app.tsx
  src/web/app/src/pages/index.tsx
  src/web/app/src/styles/telescope-post-content.css
  src/web/app/src/theme/index.ts
Labels: area: front-end

#3769 Add search and dependencies to banner buttons
  src/web/app/src/components/BannerButtons.tsx
Labels: area: front-end

#3770 fix: remove package manager from vscode settings
  .vscode/settings.json
Labels: developer experience

#3767 Fixing 'About Us' wrong hyperlink
  src/web/app/src/components/BannerButtons.tsx
Labels: area: front-end
