Repository Seneca-CDOT/telescope, pull requests merged in 2022-01, with the labels that each got.

#2641 Update AboutFooter snapshot and mock Date function
  src/web/src/components/AboutFooter.test.tsx
  src/web/src/components/__snapshots__/AboutFooter.test.tsx.snap
Labels: type: test

#2643 Make renovate use semver for Satellite
  .github/renovate.json
Labels: area: deployment

#2647 Fix student quotes mismatch quote urls
  src/web/src/components/Banner.tsx
Labels: area: front-end

#2651 Fixed Issue #2627: Changed naming of Users to Users/Org
  src/web/src/components/Posts/Users.tsx
Labels: area: front-end

#2654 Format numbers with decimal separator in dashboard
  src/api/status/src/server.js
  src/api/status/src/views/partials/commitCard.hbs
  src/api/status/src/views/partials/jobCountCard.hbs
  src/api/status/src/views/partials/totalFeedCard.hbs
  src/api/status/src/views/partials/totalPostCard.hbs
Labels: area: dashboard

#2657 Bump up to 20s time out
  jest.config.base.js
Labels: area: CI/CD, type: test

#2656 Change auto deployment links
  src/api/status/public/js/build-log/api.js
  src/api/status/src/server.js
  tools/autodeployment/README.md
Labels: rebase

#2664 Use the latest satellite version
  pnpm-lock.yaml
  src/api/auth/package.json
  src/api/feed-discovery/package.json
  src/api/image/package.json
  src/api/parser/package.json
  src/api/planet/package.json
  src/api/posts/package.json
  src/api/search/package.json
  src/api/status/package.json
  src/api/users/package.json
Labels: dependencies

#2670 Add autodeployment server to the status checks
  src/api/status/src/services.js
Labels: area: dashboard

#2673 feat: add link to planet version of telescope
  src/web/src/components/Banner.tsx
Labels: area: front-end

#2669 Improved build log page for issue 2622
  src/api/status/public/js/build-log/api.js
  src/api/status/public/js/build-log/build-header.js
  src/api/status/src/views/builds.hbs
Labels: area: dashboard

#2681 increase max_pull_requests to 250
  release-changelog-builder-config.json
Labels: area: CI/CD, area: autodeployment

#2653 Cache and display build logs
  pnpm-lock.yaml
  src/api/status/public/js/build-log/api.js
  src/api/status/public/js/build-log/build-header.js
  src/api/status/public/js/build-log/check-build-status.js
  src/api/status/public/js/build-log/check-for-build.js
  tools/autodeployment/builds.js
  tools/autodeployment/package.json
  tools/autodeployment/server.js
Labels: area: autodeployment, area: dashboard

#2686 Fix CSP error and build log crashes in dashboard
  src/api/status/env.local
  src/api/status/public/js/build-log/build-header.js
  src/api/status/src/server.js
  tools/autodeployment/builds.js
Labels: area: autodeployment, area: dashboard

#2687 Fix WEB_URL env config for status service
  docker/docker-compose.yml
  src/api/status/env.local
Labels: area: autodeployment, area: microservices, area: dashboard

#2617 added advanced search query for elasticsearch
  src/api/search/src/bin/validation.js
  src/api/search/src/routes/query.js
  src/api/search/src/search.js
Labels: area: elasticsearch

#2699 2698: Remove advanced search validation breaking production search
  src/api/search/src/bin/validation.js
Labels: area: elasticsearch

#2712 Renovate: disallow node-fetch >= 3.0 and increase renovate schedule
  .github/renovate.json
Labels: dependencies

#2723 Add YouTube channel test case for feed discovery service
  src/api/feed-discovery/test/router.test.js
Labels: area: back-end, type: test

#2726 Fix sidebar Safari css bug
  src/web/src/components/Posts/Post.tsx
Labels: area: front-end, area: css styling

#2742 Fixes #2711: Security update for node-fetch
  package.json
  pnpm-lock.yaml
  tools/migrate/package.json
Labels: type: security, dependencies

#2752 Rename auth container to sso, to prepare for supabase auth container
  .gitpod.yml
  config/env.development
  config/env.production
  config/env.staging
  docker/development.yml
  docker/docker-compose.yml
  docker/gitpod.yml
  docker/production.yml
  docs/architecture.md
  docs/environment-setup.md
  jest-playwright.config.js
  jest.config.e2e.js
  pnpm-lock.yaml
  src/api/auth/src/server.js
  src/api/readme.md
  src/api/sso/.dockerignore
  src/api/sso/Dockerfile
  src/api/sso/env.local
  src/api/sso/jest-playwright.config.js
  src/api/sso/jest.config.e2e.js
  src/api/sso/jest.config.js
  src/api/sso/package.json
  src/api/sso/src/authentication.js
  src/api/sso/src/index.js
  src/api/sso/src/middleware.js
  src/api/sso/src/roles.js
  src/api/sso/src/routes/index.js
  src/api/sso/src/routes/login.js
  src/api/sso/src/routes/logout.js
  src/api/sso/src/routes/register.js
  src/api/sso/src/routes/saml-metadata.js
  src/api/sso/src/server.js
  src/api/sso/src/token.js
  src/api/sso/src/user.js
  src/api/sso/src/util.js
  src/api/sso/test/e2e/auth-flows.test.js
  src/api/sso/test/e2e/routes.test.js
  src/api/sso/test/e2e/signup-flow.test.js
  src/api/sso/test/e2e/super-user.test.js
  src/api/sso/test/e2e/utils.js
  src/api/sso/test/roles.test.js
  src/api/sso/test/token.test.js
  src/api/sso/test/user.test.js
  src/api/sso/test/util.test.js
  src/api/status/src/services.js
  src/web/Dockerfile
  src/web/next.config.js
  src/web/src/config.ts
  src/web/src/pages/signup.tsx
  test/test-web-content/auth.html
  test/test-web-content/manual-auth/index.html
Labels: area: docker, area: sso, area: microservices

#2695 Switch autodeployment server to use streaming cache for build logs
  pnpm-lock.yaml
  tools/autodeployment/builds.js
  tools/autodeployment/package.json
  tools/autodeployment/server.js
Labels: area: autodeployment

#2762 Always send a build's code as part of /status info
  tools/autodeployment/builds.js
Labels: area: autodeployment

#2744 Add support for expo mobile dev
  .eslintrc.js
  package.json
  pnpm-lock.yaml
  src/mobile/.expo-shared/assets.json
  src/mobile/.gitignore
  src/mobile/App.jsx
  src/mobile/app.json
  src/mobile/assets/adaptive-icon.png
  src/mobile/assets/favicon.png
  src/mobile/assets/icon.png
  src/mobile/assets/splash.png
  src/mobile/babel.config.js
  src/mobile/metro.config.js
  src/mobile/package.json
Labels: area: back-end, area: React Native

#2763 Fixes #2671: Add vite to dashboard
  pnpm-lock.yaml
  src/api/status/.gitignore
  src/api/status/Dockerfile
  src/api/status/package.json
  src/api/status/src/server.js
  src/api/status/src/views/builds.hbs
  src/api/status/src/views/layouts/main.hbs
  src/api/status/src/views/status.hbs
  src/api/status/vite.config.js
Labels: area: tools, dependencies, area: dashboard

#2766 Bump expo deps in src/mobile
  src/mobile/package.json
Labels: area: React Native

#2756 Better SHA extraction from GitHub webhook payloads
  tools/autodeployment/builds.js
  tools/autodeployment/webhook.js
Labels: area: autodeployment

#2748 Rework auth Dockerfile so it builds on M1
  src/api/sso/Dockerfile
Labels: area: docker

#2784 2nd draft for Registering an Image
  .github/workflows/deploy-feed-discovery-image.yaml
Labels: type: enhancement, area: docker, area: deployment, area: microservices
