Repository Seneca-CDOT/telescope, pull requests merged in 2023-01, with the labels that each got.

#3784 chore: update jsonwebtoken to v9
  pnpm-lock.yaml
  src/api/sso/package.json
  src/satellite/package.json
Labels: dependencies

#3788 Closes #3778: Update prisma
  package.json
  pnpm-lock.yaml
  src/db/package.json
Labels: dependencies, area: database

#3789 Changing Cookie to be sameSite none
  src/api/sso/src/index.js
Labels: area: sso

#3793 set trust for first proxy when env is prod
  src/satellite/src/app.js
Labels: area: sso

#3796 fix: add route for let's encrypt challenge
  config/nginx.conf.template
Labels: area: nginx

#3798 chore: remove nodejs 14 from the project
  .github/workflows/e2e-tests-ci.yml
  .github/workflows/unit-tests-ci.yml
  package.json
  src/api/parser/package.json
  src/web/docusaurus/package.json
Labels: developer experience
