Repository Seneca-CDOT/telescope, pull requests merged in 2023-10, with the labels that each got.

#3840 Fixed web link in pull request template to the new location of the co…
  .github/PULL_REQUEST_TEMPLATE.md
Labels: type: documentation (docs)

#3842 chore: change nodejs version in our ci to test v18 and v20 and update package.json files
  .github/workflows/e2e-tests-ci.yml
  .github/workflows/unit-tests-ci.yml
  pnpm-lock.yaml
  src/api/feed-discovery/package.json
  src/api/image/package.json
  src/api/parser/package.json
  src/api/posts/package.json
  src/api/search/package.json
  src/api/sso/package.json
  src/api/status/package.json
  src/satellite/package.json
  src/web/docusaurus/package.json
Labels: area: CI/CD, hacktoberfest-accepted, hacktoberfest

#3843 chore: update docusaurus to v2.4.3
  package.json
  pnpm-lock.yaml
  src/github-url-parser/.parcelrc
  src/github-url-parser/package.json
  src/github-url-parser/tsconfig.json
  src/web/docusaurus/package.json
Labels: dependencies, hacktoberfest-accepted

#3845 Closes #2812: Validate docker-compose files in
  .github/workflows/docker-files-validation.yml
Labels: area: CI/CD, hacktoberfest-accepted

#3836 Korean translation for the About page
  src/web/docusaurus/docusaurus.config.js
  src/web/docusaurus/i18n/ko/docusaurus-plugin-content-docs/current/overview.md
Labels: type: documentation (docs)
